<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Translations\CountryTranslation;
use Illuminate\Database\Seeder;

final class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = $this->getCountriesData();

        foreach ($countries as $countryData) {
            // Maintain idempotency so repeated seeds refresh metadata without duplicating rows.
            $existingCountry = Country::where('cca2', $countryData['cca2'])->first();

            if ($existingCountry) {
                $existingCountry->update([
                    'cca3'               => $countryData['cca3'],
                    'phone_calling_code' => $countryData['phone_calling_code'],
                    'flag'               => $countryData['flag'],
                    'region'             => $countryData['region'],
                    'subregion'          => $countryData['subregion'],
                    'latitude'           => $countryData['latitude'],
                    'longitude'          => $countryData['longitude'],
                    'currencies'         => $countryData['currencies'],
                ]);
                $country = $existingCountry;
            } else {
                // Create a fresh record with deterministic codes so city seeders can locate the country reliably.
                $country = Country::factory()
                    ->state([
                        'cca2'               => $countryData['cca2'],
                        'cca3'               => $countryData['cca3'],
                        'iso_code'           => strtolower($countryData['cca2']),
                        'code'               => strtolower($countryData['cca2']),
                        'phone_calling_code' => $countryData['phone_calling_code'],
                        'flag'               => $countryData['flag'],
                        'region'             => $countryData['region'],
                        'subregion'          => $countryData['subregion'],
                        'latitude'           => $countryData['latitude'],
                        'longitude'          => $countryData['longitude'],
                        'currencies'         => $countryData['currencies'],
                    ])
                    ->create();
            }

            foreach ($countryData['translations'] as $locale => $translation) {
                // Keep translations synchronised across all supported storefront languages.
                CountryTranslation::updateOrCreate([
                    'country_id' => $country->id,
                    'locale'     => $locale,
                ], [
                    'name'          => $translation['name'],
                    'name_official' => $translation['name_official'],
                ]);
            }
        }
    }

    private function getCountriesData(): array
    {
        // Only the European countries requested by the business team are seeded to match storefront coverage.
        return [
            [
                'cca2'               => 'AL',
                'cca3'               => 'ALB',
                'phone_calling_code' => '355',
                'flag'               => '🇦🇱',
                'region'             => 'Europe',
                'subregion'          => 'Southern Europe',
                'latitude'           => 41.1533,
                'longitude'          => 20.1683,
                'currencies'         => ['ALL'],
                'translations'       => [
                    'lt' => ['name' => 'Albanija', 'name_official' => 'Albanijos Respublika'],
                    'en' => ['name' => 'Albania', 'name_official' => 'Republic of Albania'],
                    'de' => ['name' => 'Albanien', 'name_official' => 'Republik Albanien'],
                    'ru' => ['name' => 'Албания', 'name_official' => 'Республика Албания'],
                ],
            ],
            [
                'cca2'               => 'AD',
                'cca3'               => 'AND',
                'phone_calling_code' => '376',
                'flag'               => '🇦🇩',
                'region'             => 'Europe',
                'subregion'          => 'Southern Europe',
                'latitude'           => 42.5063,
                'longitude'          => 1.5218,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Andora', 'name_official' => 'Andoros Kunigaikštystė'],
                    'en' => ['name' => 'Andorra', 'name_official' => 'Principality of Andorra'],
                    'de' => ['name' => 'Andorra', 'name_official' => 'Fürstentum Andorra'],
                    'ru' => ['name' => 'Андорра', 'name_official' => 'Княжество Андорра'],
                ],
            ],
            [
                'cca2'               => 'AM',
                'cca3'               => 'ARM',
                'phone_calling_code' => '374',
                'flag'               => '🇦🇲',
                'region'             => 'Europe',
                'subregion'          => 'Western Asia',
                'latitude'           => 40.0691,
                'longitude'          => 45.0382,
                'currencies'         => ['AMD'],
                'translations'       => [
                    'lt' => ['name' => 'Armėnija', 'name_official' => 'Armėnijos Respublika'],
                    'en' => ['name' => 'Armenia', 'name_official' => 'Republic of Armenia'],
                    'de' => ['name' => 'Armenien', 'name_official' => 'Republik Armenien'],
                    'ru' => ['name' => 'Армения', 'name_official' => 'Республика Армения'],
                ],
            ],
            [
                'cca2'               => 'AT',
                'cca3'               => 'AUT',
                'phone_calling_code' => '43',
                'flag'               => '🇦🇹',
                'region'             => 'Europe',
                'subregion'          => 'Central Europe',
                'latitude'           => 47.5162,
                'longitude'          => 14.5501,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Austrija', 'name_official' => 'Austrijos Respublika'],
                    'en' => ['name' => 'Austria', 'name_official' => 'Republic of Austria'],
                    'de' => ['name' => 'Österreich', 'name_official' => 'Republik Österreich'],
                    'ru' => ['name' => 'Австрия', 'name_official' => 'Республика Австрия'],
                ],
            ],
            [
                'cca2'               => 'AZ',
                'cca3'               => 'AZE',
                'phone_calling_code' => '994',
                'flag'               => '🇦🇿',
                'region'             => 'Europe',
                'subregion'          => 'Western Asia',
                'latitude'           => 40.1431,
                'longitude'          => 47.5769,
                'currencies'         => ['AZN'],
                'translations'       => [
                    'lt' => ['name' => 'Azerbaidžanas', 'name_official' => 'Azerbaidžano Respublika'],
                    'en' => ['name' => 'Azerbaijan', 'name_official' => 'Republic of Azerbaijan'],
                    'de' => ['name' => 'Aserbaidschan', 'name_official' => 'Republik Aserbaidschan'],
                    'ru' => ['name' => 'Азербайджан', 'name_official' => 'Азербайджанская Республика'],
                ],
            ],
            [
                'cca2'               => 'BE',
                'cca3'               => 'BEL',
                'phone_calling_code' => '32',
                'flag'               => '🇧🇪',
                'region'             => 'Europe',
                'subregion'          => 'Western Europe',
                'latitude'           => 50.5039,
                'longitude'          => 4.4699,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Belgija', 'name_official' => 'Belgijos Karalystė'],
                    'en' => ['name' => 'Belgium', 'name_official' => 'Kingdom of Belgium'],
                    'de' => ['name' => 'Belgien', 'name_official' => 'Königreich Belgien'],
                    'ru' => ['name' => 'Бельгия', 'name_official' => 'Королевство Бельгия'],
                ],
            ],
            [
                'cca2'               => 'BA',
                'cca3'               => 'BIH',
                'phone_calling_code' => '387',
                'flag'               => '🇧🇦',
                'region'             => 'Europe',
                'subregion'          => 'Southern Europe',
                'latitude'           => 43.9159,
                'longitude'          => 17.6791,
                'currencies'         => ['BAM'],
                'translations'       => [
                    'lt' => ['name' => 'Bosnija ir Hercegovina', 'name_official' => 'Bosnija ir Hercegovina'],
                    'en' => ['name' => 'Bosnia and Herzegovina', 'name_official' => 'Bosnia and Herzegovina'],
                    'de' => ['name' => 'Bosnien und Herzegowina', 'name_official' => 'Bosnien und Herzegowina'],
                    'ru' => ['name' => 'Босния и Герцеговина', 'name_official' => 'Босния и Герцеговина'],
                ],
            ],
            [
                'cca2'               => 'BG',
                'cca3'               => 'BGR',
                'phone_calling_code' => '359',
                'flag'               => '🇧🇬',
                'region'             => 'Europe',
                'subregion'          => 'Eastern Europe',
                'latitude'           => 42.7339,
                'longitude'          => 25.4858,
                'currencies'         => ['BGN'],
                'translations'       => [
                    'lt' => ['name' => 'Bulgarija', 'name_official' => 'Bulgarijos Respublika'],
                    'en' => ['name' => 'Bulgaria', 'name_official' => 'Republic of Bulgaria'],
                    'de' => ['name' => 'Bulgarien', 'name_official' => 'Republik Bulgarien'],
                    'ru' => ['name' => 'Болгария', 'name_official' => 'Республика Болгария'],
                ],
            ],
            [
                'cca2'               => 'HR',
                'cca3'               => 'HRV',
                'phone_calling_code' => '385',
                'flag'               => '🇭🇷',
                'region'             => 'Europe',
                'subregion'          => 'Southern Europe',
                'latitude'           => 45.1000,
                'longitude'          => 15.2000,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Kroatija', 'name_official' => 'Kroatijos Respublika'],
                    'en' => ['name' => 'Croatia', 'name_official' => 'Republic of Croatia'],
                    'de' => ['name' => 'Kroatien', 'name_official' => 'Republik Kroatien'],
                    'ru' => ['name' => 'Хорватия', 'name_official' => 'Республика Хорватия'],
                ],
            ],
            [
                'cca2'               => 'CY',
                'cca3'               => 'CYP',
                'phone_calling_code' => '357',
                'flag'               => '🇨🇾',
                'region'             => 'Europe',
                'subregion'          => 'Southern Europe',
                'latitude'           => 35.1264,
                'longitude'          => 33.4299,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Kipras', 'name_official' => 'Kipro Respublika'],
                    'en' => ['name' => 'Cyprus', 'name_official' => 'Republic of Cyprus'],
                    'de' => ['name' => 'Zypern', 'name_official' => 'Republik Zypern'],
                    'ru' => ['name' => 'Кипр', 'name_official' => 'Республика Кипр'],
                ],
            ],
            [
                'cca2'               => 'CZ',
                'cca3'               => 'CZE',
                'phone_calling_code' => '420',
                'flag'               => '🇨🇿',
                'region'             => 'Europe',
                'subregion'          => 'Central Europe',
                'latitude'           => 49.8175,
                'longitude'          => 15.4730,
                'currencies'         => ['CZK'],
                'translations'       => [
                    'lt' => ['name' => 'Čekija', 'name_official' => 'Čekijos Respublika'],
                    'en' => ['name' => 'Czech Republic', 'name_official' => 'Czech Republic'],
                    'de' => ['name' => 'Tschechien', 'name_official' => 'Tschechische Republik'],
                    'ru' => ['name' => 'Чехия', 'name_official' => 'Чешская Республика'],
                ],
            ],
            [
                'cca2'               => 'DK',
                'cca3'               => 'DNK',
                'phone_calling_code' => '45',
                'flag'               => '🇩🇰',
                'region'             => 'Europe',
                'subregion'          => 'Northern Europe',
                'latitude'           => 56.2639,
                'longitude'          => 9.5018,
                'currencies'         => ['DKK'],
                'translations'       => [
                    'lt' => ['name' => 'Danija', 'name_official' => 'Danijos Karalystė'],
                    'en' => ['name' => 'Denmark', 'name_official' => 'Kingdom of Denmark'],
                    'de' => ['name' => 'Dänemark', 'name_official' => 'Königreich Dänemark'],
                    'ru' => ['name' => 'Дания', 'name_official' => 'Королевство Дания'],
                ],
            ],
            [
                'cca2'               => 'EE',
                'cca3'               => 'EST',
                'phone_calling_code' => '372',
                'flag'               => '🇪🇪',
                'region'             => 'Europe',
                'subregion'          => 'Northern Europe',
                'latitude'           => 58.5953,
                'longitude'          => 25.0136,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Estija', 'name_official' => 'Estijos Respublika'],
                    'en' => ['name' => 'Estonia', 'name_official' => 'Republic of Estonia'],
                    'de' => ['name' => 'Estland', 'name_official' => 'Republik Estland'],
                    'ru' => ['name' => 'Эстония', 'name_official' => 'Эстонская Республика'],
                ],
            ],
            [
                'cca2'               => 'FI',
                'cca3'               => 'FIN',
                'phone_calling_code' => '358',
                'flag'               => '🇫🇮',
                'region'             => 'Europe',
                'subregion'          => 'Northern Europe',
                'latitude'           => 61.9241,
                'longitude'          => 25.7482,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Suomija', 'name_official' => 'Suomijos Respublika'],
                    'en' => ['name' => 'Finland', 'name_official' => 'Republic of Finland'],
                    'de' => ['name' => 'Finnland', 'name_official' => 'Republik Finnland'],
                    'ru' => ['name' => 'Финляндия', 'name_official' => 'Финляндская Республика'],
                ],
            ],
            [
                'cca2'               => 'FR',
                'cca3'               => 'FRA',
                'phone_calling_code' => '33',
                'flag'               => '🇫🇷',
                'region'             => 'Europe',
                'subregion'          => 'Western Europe',
                'latitude'           => 46.2276,
                'longitude'          => 2.2137,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Prancūzija', 'name_official' => 'Prancūzijos Respublika'],
                    'en' => ['name' => 'France', 'name_official' => 'French Republic'],
                    'de' => ['name' => 'Frankreich', 'name_official' => 'Französische Republik'],
                    'ru' => ['name' => 'Франция', 'name_official' => 'Французская Республика'],
                ],
            ],
            [
                'cca2'               => 'GE',
                'cca3'               => 'GEO',
                'phone_calling_code' => '995',
                'flag'               => '🇬🇪',
                'region'             => 'Europe',
                'subregion'          => 'Western Asia',
                'latitude'           => 42.3154,
                'longitude'          => 43.3569,
                'currencies'         => ['GEL'],
                'translations'       => [
                    'lt' => ['name' => 'Gruzija', 'name_official' => 'Sakartvelas'],
                    'en' => ['name' => 'Georgia', 'name_official' => 'Georgia'],
                    'de' => ['name' => 'Georgien', 'name_official' => 'Georgien'],
                    'ru' => ['name' => 'Грузия', 'name_official' => 'Грузия'],
                ],
            ],
            [
                'cca2'               => 'DE',
                'cca3'               => 'DEU',
                'phone_calling_code' => '49',
                'flag'               => '🇩🇪',
                'region'             => 'Europe',
                'subregion'          => 'Western Europe',
                'latitude'           => 51.1657,
                'longitude'          => 10.4515,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Vokietija', 'name_official' => 'Vokietijos Federacinė Respublika'],
                    'en' => ['name' => 'Germany', 'name_official' => 'Federal Republic of Germany'],
                    'de' => ['name' => 'Deutschland', 'name_official' => 'Bundesrepublik Deutschland'],
                    'ru' => ['name' => 'Германия', 'name_official' => 'Федеративная Республика Германия'],
                ],
            ],
            [
                'cca2'               => 'GR',
                'cca3'               => 'GRC',
                'phone_calling_code' => '30',
                'flag'               => '🇬🇷',
                'region'             => 'Europe',
                'subregion'          => 'Southern Europe',
                'latitude'           => 39.0742,
                'longitude'          => 21.8243,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Graikija', 'name_official' => 'Graikijos Respublika'],
                    'en' => ['name' => 'Greece', 'name_official' => 'Hellenic Republic'],
                    'de' => ['name' => 'Griechenland', 'name_official' => 'Hellenische Republik'],
                    'ru' => ['name' => 'Греция', 'name_official' => 'Греческая Республика'],
                ],
            ],
            [
                'cca2'               => 'HU',
                'cca3'               => 'HUN',
                'phone_calling_code' => '36',
                'flag'               => '🇭🇺',
                'region'             => 'Europe',
                'subregion'          => 'Central Europe',
                'latitude'           => 47.1625,
                'longitude'          => 19.5033,
                'currencies'         => ['HUF'],
                'translations'       => [
                    'lt' => ['name' => 'Vengrija', 'name_official' => 'Vengrija'],
                    'en' => ['name' => 'Hungary', 'name_official' => 'Hungary'],
                    'de' => ['name' => 'Ungarn', 'name_official' => 'Ungarn'],
                    'ru' => ['name' => 'Венгрия', 'name_official' => 'Венгрия'],
                ],
            ],
            [
                'cca2'               => 'IS',
                'cca3'               => 'ISL',
                'phone_calling_code' => '354',
                'flag'               => '🇮🇸',
                'region'             => 'Europe',
                'subregion'          => 'Northern Europe',
                'latitude'           => 64.9631,
                'longitude'          => -19.0208,
                'currencies'         => ['ISK'],
                'translations'       => [
                    'lt' => ['name' => 'Islandija', 'name_official' => 'Islandijos Respublika'],
                    'en' => ['name' => 'Iceland', 'name_official' => 'Republic of Iceland'],
                    'de' => ['name' => 'Island', 'name_official' => 'Republik Island'],
                    'ru' => ['name' => 'Исландия', 'name_official' => 'Республика Исландия'],
                ],
            ],
            [
                'cca2'               => 'IE',
                'cca3'               => 'IRL',
                'phone_calling_code' => '353',
                'flag'               => '🇮🇪',
                'region'             => 'Europe',
                'subregion'          => 'Northern Europe',
                'latitude'           => 53.1424,
                'longitude'          => -7.6921,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Airija', 'name_official' => 'Airijos Respublika'],
                    'en' => ['name' => 'Ireland', 'name_official' => 'Republic of Ireland'],
                    'de' => ['name' => 'Irland', 'name_official' => 'Republik Irland'],
                    'ru' => ['name' => 'Ирландия', 'name_official' => 'Республика Ирландия'],
                ],
            ],
            [
                'cca2'               => 'IT',
                'cca3'               => 'ITA',
                'phone_calling_code' => '39',
                'flag'               => '🇮🇹',
                'region'             => 'Europe',
                'subregion'          => 'Southern Europe',
                'latitude'           => 41.8719,
                'longitude'          => 12.5674,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Italija', 'name_official' => 'Italijos Respublika'],
                    'en' => ['name' => 'Italy', 'name_official' => 'Italian Republic'],
                    'de' => ['name' => 'Italien', 'name_official' => 'Italienische Republik'],
                    'ru' => ['name' => 'Италия', 'name_official' => 'Итальянская Республика'],
                ],
            ],
            [
                'cca2'               => 'KZ',
                'cca3'               => 'KAZ',
                'phone_calling_code' => '7',
                'flag'               => '🇰🇿',
                'region'             => 'Europe',
                'subregion'          => 'Central Asia',
                'latitude'           => 48.0196,
                'longitude'          => 66.9237,
                'currencies'         => ['KZT'],
                'translations'       => [
                    'lt' => ['name' => 'Kazachstanas', 'name_official' => 'Kazachstano Respublika'],
                    'en' => ['name' => 'Kazakhstan', 'name_official' => 'Republic of Kazakhstan'],
                    'de' => ['name' => 'Kasachstan', 'name_official' => 'Republik Kasachstan'],
                    'ru' => ['name' => 'Казахстан', 'name_official' => 'Республика Казахстан'],
                ],
            ],
            [
                'cca2'               => 'XK',
                'cca3'               => 'XKX',
                'phone_calling_code' => '383',
                'flag'               => '🇽🇰',
                'region'             => 'Europe',
                'subregion'          => 'Southern Europe',
                'latitude'           => 42.6026,
                'longitude'          => 20.9030,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Kosovas', 'name_official' => 'Kosovo Respublika'],
                    'en' => ['name' => 'Kosovo', 'name_official' => 'Republic of Kosovo'],
                    'de' => ['name' => 'Kosovo', 'name_official' => 'Republik Kosovo'],
                    'ru' => ['name' => 'Косово', 'name_official' => 'Республика Косово'],
                ],
            ],
            [
                'cca2'               => 'LV',
                'cca3'               => 'LVA',
                'phone_calling_code' => '371',
                'flag'               => '🇱🇻',
                'region'             => 'Europe',
                'subregion'          => 'Northern Europe',
                'latitude'           => 56.8796,
                'longitude'          => 24.6032,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Latvija', 'name_official' => 'Latvijos Respublika'],
                    'en' => ['name' => 'Latvia', 'name_official' => 'Republic of Latvia'],
                    'de' => ['name' => 'Lettland', 'name_official' => 'Republik Lettland'],
                    'ru' => ['name' => 'Латвия', 'name_official' => 'Латвийская Республика'],
                ],
            ],
            [
                'cca2'               => 'LI',
                'cca3'               => 'LIE',
                'phone_calling_code' => '423',
                'flag'               => '🇱🇮',
                'region'             => 'Europe',
                'subregion'          => 'Western Europe',
                'latitude'           => 47.1660,
                'longitude'          => 9.5554,
                'currencies'         => ['CHF'],
                'translations'       => [
                    'lt' => ['name' => 'Lichtenšteinas', 'name_official' => 'Lichtenšteino Kunigaikštystė'],
                    'en' => ['name' => 'Liechtenstein', 'name_official' => 'Principality of Liechtenstein'],
                    'de' => ['name' => 'Liechtenstein', 'name_official' => 'Fürstentum Liechtenstein'],
                    'ru' => ['name' => 'Лихтенштейн', 'name_official' => 'Княжество Лихтенштейн'],
                ],
            ],
            [
                'cca2'               => 'LT',
                'cca3'               => 'LTU',
                'phone_calling_code' => '370',
                'flag'               => '🇱🇹',
                'region'             => 'Europe',
                'subregion'          => 'Northern Europe',
                'latitude'           => 55.1694,
                'longitude'          => 23.8813,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Lietuva', 'name_official' => 'Lietuvos Respublika'],
                    'en' => ['name' => 'Lithuania', 'name_official' => 'Republic of Lithuania'],
                    'de' => ['name' => 'Litauen', 'name_official' => 'Republik Litauen'],
                    'ru' => ['name' => 'Литва', 'name_official' => 'Литовская Республика'],
                ],
            ],
            [
                'cca2'               => 'LU',
                'cca3'               => 'LUX',
                'phone_calling_code' => '352',
                'flag'               => '🇱🇺',
                'region'             => 'Europe',
                'subregion'          => 'Western Europe',
                'latitude'           => 49.8153,
                'longitude'          => 6.1296,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Liuksemburgas', 'name_official' => 'Liuksemburgo Didžioji Hercogystė'],
                    'en' => ['name' => 'Luxembourg', 'name_official' => 'Grand Duchy of Luxembourg'],
                    'de' => ['name' => 'Luxemburg', 'name_official' => 'Großherzogtum Luxemburg'],
                    'ru' => ['name' => 'Люксембург', 'name_official' => 'Великое Герцогство Люксембург'],
                ],
            ],
            [
                'cca2'               => 'MT',
                'cca3'               => 'MLT',
                'phone_calling_code' => '356',
                'flag'               => '🇲🇹',
                'region'             => 'Europe',
                'subregion'          => 'Southern Europe',
                'latitude'           => 35.9375,
                'longitude'          => 14.3754,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Malta', 'name_official' => 'Maltos Respublika'],
                    'en' => ['name' => 'Malta', 'name_official' => 'Republic of Malta'],
                    'de' => ['name' => 'Malta', 'name_official' => 'Republik Malta'],
                    'ru' => ['name' => 'Мальта', 'name_official' => 'Республика Мальта'],
                ],
            ],
            [
                'cca2'               => 'MD',
                'cca3'               => 'MDA',
                'phone_calling_code' => '373',
                'flag'               => '🇲🇩',
                'region'             => 'Europe',
                'subregion'          => 'Eastern Europe',
                'latitude'           => 47.4116,
                'longitude'          => 28.3699,
                'currencies'         => ['MDL'],
                'translations'       => [
                    'lt' => ['name' => 'Moldova', 'name_official' => 'Moldovos Respublika'],
                    'en' => ['name' => 'Moldova', 'name_official' => 'Republic of Moldova'],
                    'de' => ['name' => 'Moldau', 'name_official' => 'Republik Moldau'],
                    'ru' => ['name' => 'Молдова', 'name_official' => 'Республика Молдова'],
                ],
            ],
            [
                'cca2'               => 'MC',
                'cca3'               => 'MCO',
                'phone_calling_code' => '377',
                'flag'               => '🇲🇨',
                'region'             => 'Europe',
                'subregion'          => 'Western Europe',
                'latitude'           => 43.7384,
                'longitude'          => 7.4246,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Monakas', 'name_official' => 'Monako Kunigaikštystė'],
                    'en' => ['name' => 'Monaco', 'name_official' => 'Principality of Monaco'],
                    'de' => ['name' => 'Monaco', 'name_official' => 'Fürstentum Monaco'],
                    'ru' => ['name' => 'Монако', 'name_official' => 'Княжество Монако'],
                ],
            ],
            [
                'cca2'               => 'ME',
                'cca3'               => 'MNE',
                'phone_calling_code' => '382',
                'flag'               => '🇲🇪',
                'region'             => 'Europe',
                'subregion'          => 'Southern Europe',
                'latitude'           => 42.7087,
                'longitude'          => 19.3744,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Juodkalnija', 'name_official' => 'Juodkalnijos Respublika'],
                    'en' => ['name' => 'Montenegro', 'name_official' => 'Montenegro'],
                    'de' => ['name' => 'Montenegro', 'name_official' => 'Montenegro'],
                    'ru' => ['name' => 'Черногория', 'name_official' => 'Черногория'],
                ],
            ],
            [
                'cca2'               => 'NL',
                'cca3'               => 'NLD',
                'phone_calling_code' => '31',
                'flag'               => '🇳🇱',
                'region'             => 'Europe',
                'subregion'          => 'Western Europe',
                'latitude'           => 52.1326,
                'longitude'          => 5.2913,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Nyderlandai', 'name_official' => 'Nyderlandų Karalystė'],
                    'en' => ['name' => 'Netherlands', 'name_official' => 'Kingdom of the Netherlands'],
                    'de' => ['name' => 'Niederlande', 'name_official' => 'Königreich der Niederlande'],
                    'ru' => ['name' => 'Нидерланды', 'name_official' => 'Королевство Нидерландов'],
                ],
            ],
            [
                'cca2'               => 'MK',
                'cca3'               => 'MKD',
                'phone_calling_code' => '389',
                'flag'               => '🇲🇰',
                'region'             => 'Europe',
                'subregion'          => 'Southern Europe',
                'latitude'           => 41.6086,
                'longitude'          => 21.7453,
                'currencies'         => ['MKD'],
                'translations'       => [
                    'lt' => ['name' => 'Šiaurės Makedonija', 'name_official' => 'Šiaurės Makedonijos Respublika'],
                    'en' => ['name' => 'North Macedonia', 'name_official' => 'Republic of North Macedonia'],
                    'de' => ['name' => 'Nordmazedonien', 'name_official' => 'Republik Nordmazedonien'],
                    'ru' => ['name' => 'Северная Македония', 'name_official' => 'Республика Северная Македония'],
                ],
            ],
            [
                'cca2'               => 'NO',
                'cca3'               => 'NOR',
                'phone_calling_code' => '47',
                'flag'               => '🇳🇴',
                'region'             => 'Europe',
                'subregion'          => 'Northern Europe',
                'latitude'           => 60.4720,
                'longitude'          => 8.4689,
                'currencies'         => ['NOK'],
                'translations'       => [
                    'lt' => ['name' => 'Norvegija', 'name_official' => 'Norvegijos Karalystė'],
                    'en' => ['name' => 'Norway', 'name_official' => 'Kingdom of Norway'],
                    'de' => ['name' => 'Norwegen', 'name_official' => 'Königreich Norwegen'],
                    'ru' => ['name' => 'Норвегия', 'name_official' => 'Королевство Норвегия'],
                ],
            ],
            [
                'cca2'               => 'PL',
                'cca3'               => 'POL',
                'phone_calling_code' => '48',
                'flag'               => '🇵🇱',
                'region'             => 'Europe',
                'subregion'          => 'Central Europe',
                'latitude'           => 51.9194,
                'longitude'          => 19.1451,
                'currencies'         => ['PLN'],
                'translations'       => [
                    'lt' => ['name' => 'Lenkija', 'name_official' => 'Lenkijos Respublika'],
                    'en' => ['name' => 'Poland', 'name_official' => 'Republic of Poland'],
                    'de' => ['name' => 'Polen', 'name_official' => 'Republik Polen'],
                    'ru' => ['name' => 'Польша', 'name_official' => 'Республика Польша'],
                ],
            ],
            [
                'cca2'               => 'PT',
                'cca3'               => 'PRT',
                'phone_calling_code' => '351',
                'flag'               => '🇵🇹',
                'region'             => 'Europe',
                'subregion'          => 'Southern Europe',
                'latitude'           => 39.3999,
                'longitude'          => -8.2245,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Portugalija', 'name_official' => 'Portugalijos Respublika'],
                    'en' => ['name' => 'Portugal', 'name_official' => 'Portuguese Republic'],
                    'de' => ['name' => 'Portugal', 'name_official' => 'Portugiesische Republik'],
                    'ru' => ['name' => 'Португалия', 'name_official' => 'Португальская Республика'],
                ],
            ],
            [
                'cca2'               => 'RO',
                'cca3'               => 'ROU',
                'phone_calling_code' => '40',
                'flag'               => '🇷🇴',
                'region'             => 'Europe',
                'subregion'          => 'Eastern Europe',
                'latitude'           => 45.9432,
                'longitude'          => 24.9668,
                'currencies'         => ['RON'],
                'translations'       => [
                    'lt' => ['name' => 'Rumunija', 'name_official' => 'Rumunija'],
                    'en' => ['name' => 'Romania', 'name_official' => 'Romania'],
                    'de' => ['name' => 'Rumänien', 'name_official' => 'Rumänien'],
                    'ru' => ['name' => 'Румыния', 'name_official' => 'Румыния'],
                ],
            ],
            [
                'cca2'               => 'SM',
                'cca3'               => 'SMR',
                'phone_calling_code' => '378',
                'flag'               => '🇸🇲',
                'region'             => 'Europe',
                'subregion'          => 'Southern Europe',
                'latitude'           => 43.9424,
                'longitude'          => 12.4578,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'San Marinas', 'name_official' => 'San Marino Respublika'],
                    'en' => ['name' => 'San Marino', 'name_official' => 'Republic of San Marino'],
                    'de' => ['name' => 'San Marino', 'name_official' => 'Republik San Marino'],
                    'ru' => ['name' => 'Сан-Марино', 'name_official' => 'Республика Сан-Марино'],
                ],
            ],
            [
                'cca2'               => 'RS',
                'cca3'               => 'SRB',
                'phone_calling_code' => '381',
                'flag'               => '🇷🇸',
                'region'             => 'Europe',
                'subregion'          => 'Southern Europe',
                'latitude'           => 44.0165,
                'longitude'          => 21.0059,
                'currencies'         => ['RSD'],
                'translations'       => [
                    'lt' => ['name' => 'Serbija', 'name_official' => 'Serbijos Respublika'],
                    'en' => ['name' => 'Serbia', 'name_official' => 'Republic of Serbia'],
                    'de' => ['name' => 'Serbien', 'name_official' => 'Republik Serbien'],
                    'ru' => ['name' => 'Сербия', 'name_official' => 'Республика Сербия'],
                ],
            ],
            [
                'cca2'               => 'SK',
                'cca3'               => 'SVK',
                'phone_calling_code' => '421',
                'flag'               => '🇸🇰',
                'region'             => 'Europe',
                'subregion'          => 'Central Europe',
                'latitude'           => 48.6690,
                'longitude'          => 19.6990,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Slovakija', 'name_official' => 'Slovakijos Respublika'],
                    'en' => ['name' => 'Slovakia', 'name_official' => 'Slovak Republic'],
                    'de' => ['name' => 'Slowakei', 'name_official' => 'Slowakische Republik'],
                    'ru' => ['name' => 'Словакия', 'name_official' => 'Словацкая Республика'],
                ],
            ],
            [
                'cca2'               => 'SI',
                'cca3'               => 'SVN',
                'phone_calling_code' => '386',
                'flag'               => '🇸🇮',
                'region'             => 'Europe',
                'subregion'          => 'Southern Europe',
                'latitude'           => 46.1512,
                'longitude'          => 14.9955,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Slovėnija', 'name_official' => 'Slovėnijos Respublika'],
                    'en' => ['name' => 'Slovenia', 'name_official' => 'Republic of Slovenia'],
                    'de' => ['name' => 'Slowenien', 'name_official' => 'Republik Slowenien'],
                    'ru' => ['name' => 'Словения', 'name_official' => 'Республика Словения'],
                ],
            ],
            [
                'cca2'               => 'ES',
                'cca3'               => 'ESP',
                'phone_calling_code' => '34',
                'flag'               => '🇪🇸',
                'region'             => 'Europe',
                'subregion'          => 'Southern Europe',
                'latitude'           => 40.4637,
                'longitude'          => -3.7492,
                'currencies'         => ['EUR'],
                'translations'       => [
                    'lt' => ['name' => 'Ispanija', 'name_official' => 'Ispanijos Karalystė'],
                    'en' => ['name' => 'Spain', 'name_official' => 'Kingdom of Spain'],
                    'de' => ['name' => 'Spanien', 'name_official' => 'Königreich Spanien'],
                    'ru' => ['name' => 'Испания', 'name_official' => 'Королевство Испания'],
                ],
            ],
            [
                'cca2'               => 'SE',
                'cca3'               => 'SWE',
                'phone_calling_code' => '46',
                'flag'               => '🇸🇪',
                'region'             => 'Europe',
                'subregion'          => 'Northern Europe',
                'latitude'           => 60.1282,
                'longitude'          => 18.6435,
                'currencies'         => ['SEK'],
                'translations'       => [
                    'lt' => ['name' => 'Švedija', 'name_official' => 'Švedijos Karalystė'],
                    'en' => ['name' => 'Sweden', 'name_official' => 'Kingdom of Sweden'],
                    'de' => ['name' => 'Schweden', 'name_official' => 'Königreich Schweden'],
                    'ru' => ['name' => 'Швеция', 'name_official' => 'Королевство Швеция'],
                ],
            ],
            [
                'cca2'               => 'CH',
                'cca3'               => 'CHE',
                'phone_calling_code' => '41',
                'flag'               => '🇨🇭',
                'region'             => 'Europe',
                'subregion'          => 'Western Europe',
                'latitude'           => 46.8182,
                'longitude'          => 8.2275,
                'currencies'         => ['CHF'],
                'translations'       => [
                    'lt' => ['name' => 'Šveicarija', 'name_official' => 'Šveicarijos Konfederacija'],
                    'en' => ['name' => 'Switzerland', 'name_official' => 'Swiss Confederation'],
                    'de' => ['name' => 'Schweiz', 'name_official' => 'Schweizerische Eidgenossenschaft'],
                    'ru' => ['name' => 'Швейцария', 'name_official' => 'Швейцарская Конфедерация'],
                ],
            ],
            [
                'cca2'               => 'TR',
                'cca3'               => 'TUR',
                'phone_calling_code' => '90',
                'flag'               => '🇹🇷',
                'region'             => 'Europe',
                'subregion'          => 'Western Asia',
                'latitude'           => 38.9637,
                'longitude'          => 35.2433,
                'currencies'         => ['TRY'],
                'translations'       => [
                    'lt' => ['name' => 'Turkija', 'name_official' => 'Turkijos Respublika'],
                    'en' => ['name' => 'Turkey', 'name_official' => 'Republic of Turkey'],
                    'de' => ['name' => 'Türkei', 'name_official' => 'Republik Türkei'],
                    'ru' => ['name' => 'Турция', 'name_official' => 'Турецкая Республика'],
                ],
            ],
            [
                'cca2'               => 'UA',
                'cca3'               => 'UKR',
                'phone_calling_code' => '380',
                'flag'               => '🇺🇦',
                'region'             => 'Europe',
                'subregion'          => 'Eastern Europe',
                'latitude'           => 48.3794,
                'longitude'          => 31.1656,
                'currencies'         => ['UAH'],
                'translations'       => [
                    'lt' => ['name' => 'Ukraina', 'name_official' => 'Ukraina'],
                    'en' => ['name' => 'Ukraine', 'name_official' => 'Ukraine'],
                    'de' => ['name' => 'Ukraine', 'name_official' => 'Ukraine'],
                    'ru' => ['name' => 'Украина', 'name_official' => 'Украина'],
                ],
            ],
            [
                'cca2'               => 'GB',
                'cca3'               => 'GBR',
                'phone_calling_code' => '44',
                'flag'               => '🇬🇧',
                'region'             => 'Europe',
                'subregion'          => 'Northern Europe',
                'latitude'           => 55.3781,
                'longitude'          => -3.4360,
                'currencies'         => ['GBP'],
                'translations'       => [
                    'lt' => ['name' => 'Jungtinė Karalystė', 'name_official' => 'Didžiosios Britanijos ir Šiaurės Airijos Jungtinė Karalystė'],
                    'en' => ['name' => 'United Kingdom', 'name_official' => 'United Kingdom of Great Britain and Northern Ireland'],
                    'de' => ['name' => 'Vereinigtes Königreich', 'name_official' => 'Vereinigtes Königreich Großbritannien und Nordirland'],
                    'ru' => ['name' => 'Соединённое Королевство', 'name_official' => 'Соединённое Королевство Великобритании и Северной Ирландии'],
                ],
            ],
        ];
    }
}
