<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Discount;

final class DiscountSeeder extends BaseSeeder
{
    public function run(): void
    {
        $now = now();

        $discounts = [
            [
                'slug'                  => 'sitewide-05',
                'name'                  => 'Sitewide 5%',
                'description'           => 'Base percentage discount for all carts.',
                'type'                  => 'percentage',
                'value'                 => 5.0,
                'is_active'             => true,
                'is_enabled'            => true,
                'starts_at'             => $now->copy()->subDays(30),
                'ends_at'               => $now->copy()->addDays(120),
                'usage_limit'           => null,
                'usage_count'           => 0,
                'minimum_amount'        => 0,
                'maximum_amount'        => 500,
                'status'                => 'active',
                'scope'                 => ['cart'],
                'stacking_policy'       => 'stackable',
                'metadata'              => ['seed' => true, 'segment' => 'all'],
                'priority'              => 5,
                'exclusive'             => false,
                'applies_to_shipping'   => false,
                'free_shipping'         => false,
                'first_order_only'      => false,
                'per_customer_limit'    => null,
                'per_code_limit'        => null,
                'per_day_limit'         => null,
                'channel_restrictions'  => ['web', 'admin'],
                'currency_restrictions' => ['EUR'],
                'weekday_mask'          => '1111111',
                'time_window'           => ['start' => '00:00', 'end' => '23:59'],
            ],
            [
                'slug'                  => 'cart-amount-10',
                'name'                  => 'Cart €10 Off',
                'description'           => 'Flat discount for medium sized orders.',
                'type'                  => 'fixed',
                'value'                 => 10.0,
                'is_active'             => true,
                'is_enabled'            => true,
                'starts_at'             => $now->copy()->subDays(15),
                'ends_at'               => $now->copy()->addDays(90),
                'usage_limit'           => 5000,
                'usage_count'           => 0,
                'minimum_amount'        => 75,
                'maximum_amount'        => 10,
                'status'                => 'active',
                'scope'                 => ['cart', 'checkout'],
                'stacking_policy'       => 'single_best',
                'metadata'              => ['seed' => true, 'campaign' => 'cart-amount'],
                'priority'              => 10,
                'exclusive'             => false,
                'applies_to_shipping'   => false,
                'free_shipping'         => false,
                'first_order_only'      => false,
                'per_customer_limit'    => 5,
                'per_code_limit'        => null,
                'per_day_limit'         => 250,
                'channel_restrictions'  => ['web'],
                'currency_restrictions' => ['EUR'],
                'weekday_mask'          => '1111111',
                'time_window'           => ['start' => '06:00', 'end' => '22:00'],
            ],
            [
                'slug'                  => 'free-shipping-over-100',
                'name'                  => 'Free Shipping Over €100',
                'description'           => 'Removes shipping cost for larger orders.',
                'type'                  => 'free_shipping',
                'value'                 => 0,
                'is_active'             => true,
                'is_enabled'            => true,
                'starts_at'             => $now->copy()->subDays(7),
                'ends_at'               => $now->copy()->addDays(180),
                'usage_limit'           => null,
                'usage_count'           => 0,
                'minimum_amount'        => 100,
                'maximum_amount'        => null,
                'status'                => 'active',
                'scope'                 => ['shipping'],
                'stacking_policy'       => 'stackable',
                'metadata'              => ['seed' => true, 'shipping' => 'free'],
                'priority'              => 8,
                'exclusive'             => false,
                'applies_to_shipping'   => true,
                'free_shipping'         => true,
                'first_order_only'      => false,
                'per_customer_limit'    => null,
                'per_code_limit'        => null,
                'per_day_limit'         => null,
                'channel_restrictions'  => ['web', 'mobile'],
                'currency_restrictions' => ['EUR'],
                'weekday_mask'          => '1111111',
                'time_window'           => ['start' => '00:00', 'end' => '23:59'],
            ],
            [
                'slug'                  => 'vip-12-stack',
                'name'                  => 'VIP 12%',
                'description'           => 'Loyal customer segment discount.',
                'type'                  => 'percentage',
                'value'                 => 12.0,
                'is_active'             => true,
                'is_enabled'            => true,
                'starts_at'             => $now->copy()->subDays(10),
                'ends_at'               => $now->copy()->addDays(365),
                'usage_limit'           => null,
                'usage_count'           => 0,
                'minimum_amount'        => 0,
                'maximum_amount'        => 300,
                'status'                => 'active',
                'scope'                 => ['customer_group'],
                'stacking_policy'       => 'stackable',
                'metadata'              => ['seed' => true, 'segment' => 'vip'],
                'priority'              => 20,
                'exclusive'             => false,
                'applies_to_shipping'   => false,
                'free_shipping'         => false,
                'first_order_only'      => false,
                'per_customer_limit'    => null,
                'per_code_limit'        => null,
                'per_day_limit'         => null,
                'channel_restrictions'  => ['web', 'admin'],
                'currency_restrictions' => ['EUR'],
                'weekday_mask'          => '1111111',
                'time_window'           => ['start' => '00:00', 'end' => '23:59'],
            ],
            [
                'slug'                  => 'flash-25-exclusive',
                'name'                  => 'Flash 25% Exclusive',
                'description'           => 'Short-term exclusive promo.',
                'type'                  => 'percentage',
                'value'                 => 25.0,
                'is_active'             => true,
                'is_enabled'            => true,
                'starts_at'             => $now->copy()->subHours(2),
                'ends_at'               => $now->copy()->addDays(2),
                'usage_limit'           => 200,
                'usage_count'           => 0,
                'minimum_amount'        => 20,
                'maximum_amount'        => 200,
                'status'                => 'active',
                'scope'                 => ['cart'],
                'stacking_policy'       => 'single_best',
                'metadata'              => ['seed' => true, 'campaign' => 'flash'],
                'priority'              => 100,
                'exclusive'             => true,
                'applies_to_shipping'   => false,
                'free_shipping'         => false,
                'first_order_only'      => false,
                'per_customer_limit'    => 1,
                'per_code_limit'        => 1,
                'per_day_limit'         => 200,
                'channel_restrictions'  => ['web'],
                'currency_restrictions' => ['EUR'],
                'weekday_mask'          => '1111111',
                'time_window'           => ['start' => '09:00', 'end' => '21:00'],
            ],
            [
                'slug'                  => 'new-customer-15',
                'name'                  => 'New Customer 15%',
                'description'           => 'First order incentive discount.',
                'type'                  => 'percentage',
                'value'                 => 15.0,
                'is_active'             => true,
                'is_enabled'            => true,
                'starts_at'             => $now->copy()->subDays(1),
                'ends_at'               => $now->copy()->addDays(120),
                'usage_limit'           => null,
                'usage_count'           => 0,
                'minimum_amount'        => 30,
                'maximum_amount'        => 100,
                'status'                => 'active',
                'scope'                 => ['checkout'],
                'stacking_policy'       => 'single_best',
                'metadata'              => ['seed' => true, 'segment' => 'new_customer'],
                'priority'              => 18,
                'exclusive'             => false,
                'applies_to_shipping'   => false,
                'free_shipping'         => false,
                'first_order_only'      => true,
                'per_customer_limit'    => 1,
                'per_code_limit'        => 1,
                'per_day_limit'         => null,
                'channel_restrictions'  => ['web', 'mobile'],
                'currency_restrictions' => ['EUR'],
                'weekday_mask'          => '1111111',
                'time_window'           => ['start' => '00:00', 'end' => '23:59'],
            ],
            [
                'slug'                  => 'weekend-7',
                'name'                  => 'Weekend 7%',
                'description'           => 'Applies only during weekends.',
                'type'                  => 'percentage',
                'value'                 => 7.0,
                'is_active'             => true,
                'is_enabled'            => true,
                'starts_at'             => $now->copy()->subDays(21),
                'ends_at'               => $now->copy()->addDays(365),
                'usage_limit'           => null,
                'usage_count'           => 0,
                'minimum_amount'        => 0,
                'maximum_amount'        => 150,
                'status'                => 'active',
                'scope'                 => ['cart'],
                'stacking_policy'       => 'stackable',
                'metadata'              => ['seed' => true, 'schedule' => 'weekend'],
                'priority'              => 7,
                'exclusive'             => false,
                'applies_to_shipping'   => false,
                'free_shipping'         => false,
                'first_order_only'      => false,
                'per_customer_limit'    => null,
                'per_code_limit'        => null,
                'per_day_limit'         => null,
                'channel_restrictions'  => ['web'],
                'currency_restrictions' => ['EUR'],
                'weekday_mask'          => '0000011',
                'time_window'           => ['start' => '00:00', 'end' => '23:59'],
            ],
            [
                'slug'                  => 'weekday-b2b-9',
                'name'                  => 'Weekday B2B 9%',
                'description'           => 'Business-hours discount for weekdays.',
                'type'                  => 'percentage',
                'value'                 => 9.0,
                'is_active'             => true,
                'is_enabled'            => true,
                'starts_at'             => $now->copy()->subDays(5),
                'ends_at'               => $now->copy()->addDays(180),
                'usage_limit'           => 4000,
                'usage_count'           => 0,
                'minimum_amount'        => 60,
                'maximum_amount'        => 250,
                'status'                => 'active',
                'scope'                 => ['cart', 'customer_group'],
                'stacking_policy'       => 'stackable',
                'metadata'              => ['seed' => true, 'segment' => 'b2b'],
                'priority'              => 11,
                'exclusive'             => false,
                'applies_to_shipping'   => false,
                'free_shipping'         => false,
                'first_order_only'      => false,
                'per_customer_limit'    => 15,
                'per_code_limit'        => null,
                'per_day_limit'         => 300,
                'channel_restrictions'  => ['admin', 'api'],
                'currency_restrictions' => ['EUR', 'USD'],
                'weekday_mask'          => '1111100',
                'time_window'           => ['start' => '08:00', 'end' => '18:00'],
            ],
            [
                'slug'                  => 'bulk-order-40',
                'name'                  => 'Bulk Order €40',
                'description'           => 'Flat discount for high-value orders.',
                'type'                  => 'fixed',
                'value'                 => 40.0,
                'is_active'             => true,
                'is_enabled'            => true,
                'starts_at'             => $now->copy()->subDays(3),
                'ends_at'               => $now->copy()->addDays(60),
                'usage_limit'           => 1200,
                'usage_count'           => 0,
                'minimum_amount'        => 300,
                'maximum_amount'        => 40,
                'status'                => 'active',
                'scope'                 => ['cart'],
                'stacking_policy'       => 'single_best',
                'metadata'              => ['seed' => true, 'tier' => 'bulk'],
                'priority'              => 30,
                'exclusive'             => false,
                'applies_to_shipping'   => false,
                'free_shipping'         => false,
                'first_order_only'      => false,
                'per_customer_limit'    => 10,
                'per_code_limit'        => 2,
                'per_day_limit'         => 100,
                'channel_restrictions'  => ['web', 'admin'],
                'currency_restrictions' => ['EUR'],
                'weekday_mask'          => '1111111',
                'time_window'           => ['start' => '07:00', 'end' => '23:00'],
            ],
            [
                'slug'                  => 'shipping-cap-12',
                'name'                  => 'Shipping Discount €12',
                'description'           => 'Reduces shipping cost up to €12.',
                'type'                  => 'fixed',
                'value'                 => 12.0,
                'is_active'             => true,
                'is_enabled'            => true,
                'starts_at'             => $now->copy()->subDays(4),
                'ends_at'               => $now->copy()->addDays(120),
                'usage_limit'           => null,
                'usage_count'           => 0,
                'minimum_amount'        => 50,
                'maximum_amount'        => 12,
                'status'                => 'active',
                'scope'                 => ['shipping'],
                'stacking_policy'       => 'stackable',
                'metadata'              => ['seed' => true, 'shipping' => 'cap'],
                'priority'              => 9,
                'exclusive'             => false,
                'applies_to_shipping'   => true,
                'free_shipping'         => false,
                'first_order_only'      => false,
                'per_customer_limit'    => null,
                'per_code_limit'        => null,
                'per_day_limit'         => null,
                'channel_restrictions'  => ['web'],
                'currency_restrictions' => ['EUR'],
                'weekday_mask'          => '1111111',
                'time_window'           => ['start' => '00:00', 'end' => '23:59'],
            ],
            [
                'slug'                  => 'code-limited-18',
                'name'                  => 'Code-Limited 18%',
                'description'           => 'Higher discount with strict code limits.',
                'type'                  => 'percentage',
                'value'                 => 18.0,
                'is_active'             => true,
                'is_enabled'            => true,
                'starts_at'             => $now->copy()->subDays(2),
                'ends_at'               => $now->copy()->addDays(45),
                'usage_limit'           => 350,
                'usage_count'           => 0,
                'minimum_amount'        => 80,
                'maximum_amount'        => 220,
                'status'                => 'active',
                'scope'                 => ['checkout'],
                'stacking_policy'       => 'single_best',
                'metadata'              => ['seed' => true, 'code_mode' => 'strict'],
                'priority'              => 40,
                'exclusive'             => false,
                'applies_to_shipping'   => false,
                'free_shipping'         => false,
                'first_order_only'      => false,
                'per_customer_limit'    => 2,
                'per_code_limit'        => 1,
                'per_day_limit'         => 50,
                'channel_restrictions'  => ['web', 'mobile'],
                'currency_restrictions' => ['EUR'],
                'weekday_mask'          => '1111111',
                'time_window'           => ['start' => '10:00', 'end' => '22:00'],
            ],
            [
                'slug'                  => 'scheduled-spring-14',
                'name'                  => 'Scheduled Spring 14%',
                'description'           => 'Upcoming campaign to validate scheduled state.',
                'type'                  => 'percentage',
                'value'                 => 14.0,
                'is_active'             => true,
                'is_enabled'            => true,
                'starts_at'             => $now->copy()->addDays(10),
                'ends_at'               => $now->copy()->addDays(40),
                'usage_limit'           => 500,
                'usage_count'           => 0,
                'minimum_amount'        => 40,
                'maximum_amount'        => 130,
                'status'                => 'scheduled',
                'scope'                 => ['cart'],
                'stacking_policy'       => 'single_best',
                'metadata'              => ['seed' => true, 'state' => 'scheduled'],
                'priority'              => 14,
                'exclusive'             => false,
                'applies_to_shipping'   => false,
                'free_shipping'         => false,
                'first_order_only'      => false,
                'per_customer_limit'    => null,
                'per_code_limit'        => null,
                'per_day_limit'         => null,
                'channel_restrictions'  => ['web'],
                'currency_restrictions' => ['EUR'],
                'weekday_mask'          => '1111111',
                'time_window'           => ['start' => '00:00', 'end' => '23:59'],
            ],
            [
                'slug'                  => 'scheduled-fixed-22',
                'name'                  => 'Scheduled €22',
                'description'           => 'Upcoming fixed amount campaign.',
                'type'                  => 'fixed',
                'value'                 => 22.0,
                'is_active'             => true,
                'is_enabled'            => true,
                'starts_at'             => $now->copy()->addDays(3),
                'ends_at'               => $now->copy()->addDays(30),
                'usage_limit'           => 800,
                'usage_count'           => 0,
                'minimum_amount'        => 120,
                'maximum_amount'        => 22,
                'status'                => 'scheduled',
                'scope'                 => ['checkout'],
                'stacking_policy'       => 'single_best',
                'metadata'              => ['seed' => true, 'state' => 'scheduled'],
                'priority'              => 22,
                'exclusive'             => false,
                'applies_to_shipping'   => false,
                'free_shipping'         => false,
                'first_order_only'      => false,
                'per_customer_limit'    => 1,
                'per_code_limit'        => 1,
                'per_day_limit'         => 70,
                'channel_restrictions'  => ['web', 'admin'],
                'currency_restrictions' => ['EUR'],
                'weekday_mask'          => '1111111',
                'time_window'           => ['start' => '09:00', 'end' => '20:00'],
            ],
            [
                'slug'                  => 'expired-legacy-10',
                'name'                  => 'Expired Legacy 10%',
                'description'           => 'Historical record to validate expired state.',
                'type'                  => 'percentage',
                'value'                 => 10.0,
                'is_active'             => false,
                'is_enabled'            => true,
                'starts_at'             => $now->copy()->subDays(90),
                'ends_at'               => $now->copy()->subDays(10),
                'usage_limit'           => 10000,
                'usage_count'           => 2750,
                'minimum_amount'        => 0,
                'maximum_amount'        => 80,
                'status'                => 'expired',
                'scope'                 => ['cart'],
                'stacking_policy'       => 'stackable',
                'metadata'              => ['seed' => true, 'state' => 'expired'],
                'priority'              => 4,
                'exclusive'             => false,
                'applies_to_shipping'   => false,
                'free_shipping'         => false,
                'first_order_only'      => false,
                'per_customer_limit'    => null,
                'per_code_limit'        => null,
                'per_day_limit'         => null,
                'channel_restrictions'  => ['web'],
                'currency_restrictions' => ['EUR'],
                'weekday_mask'          => '1111111',
                'time_window'           => ['start' => '00:00', 'end' => '23:59'],
            ],
            [
                'slug'                  => 'expired-freeship-2024',
                'name'                  => 'Expired Free Shipping',
                'description'           => 'Historical free shipping campaign.',
                'type'                  => 'free_shipping',
                'value'                 => 0,
                'is_active'             => false,
                'is_enabled'            => true,
                'starts_at'             => $now->copy()->subDays(120),
                'ends_at'               => $now->copy()->subDays(15),
                'usage_limit'           => null,
                'usage_count'           => 1200,
                'minimum_amount'        => 90,
                'maximum_amount'        => null,
                'status'                => 'expired',
                'scope'                 => ['shipping'],
                'stacking_policy'       => 'stackable',
                'metadata'              => ['seed' => true, 'state' => 'expired'],
                'priority'              => 3,
                'exclusive'             => false,
                'applies_to_shipping'   => true,
                'free_shipping'         => true,
                'first_order_only'      => false,
                'per_customer_limit'    => null,
                'per_code_limit'        => null,
                'per_day_limit'         => null,
                'channel_restrictions'  => ['web'],
                'currency_restrictions' => ['EUR'],
                'weekday_mask'          => '1111111',
                'time_window'           => ['start' => '00:00', 'end' => '23:59'],
            ],
            [
                'slug'                  => 'multi-currency-11',
                'name'                  => 'Multi-Currency 11%',
                'description'           => 'Percent discount for multiple currencies.',
                'type'                  => 'percentage',
                'value'                 => 11.0,
                'is_active'             => true,
                'is_enabled'            => true,
                'starts_at'             => $now->copy()->subDays(2),
                'ends_at'               => $now->copy()->addDays(200),
                'usage_limit'           => 6000,
                'usage_count'           => 0,
                'minimum_amount'        => 30,
                'maximum_amount'        => 160,
                'status'                => 'active',
                'scope'                 => ['cart', 'channel'],
                'stacking_policy'       => 'stackable',
                'metadata'              => ['seed' => true, 'currency_mode' => 'multi'],
                'priority'              => 13,
                'exclusive'             => false,
                'applies_to_shipping'   => false,
                'free_shipping'         => false,
                'first_order_only'      => false,
                'per_customer_limit'    => 20,
                'per_code_limit'        => null,
                'per_day_limit'         => 400,
                'channel_restrictions'  => ['web', 'mobile', 'api'],
                'currency_restrictions' => ['EUR', 'USD', 'GBP'],
                'weekday_mask'          => '1111111',
                'time_window'           => ['start' => '00:00', 'end' => '23:59'],
            ],
        ];

        foreach ($discounts as $discount) {
            $this->upsertDiscount($discount);
        }

        $this->command?->info(sprintf('DiscountSeeder seeded %d discounts.', count($discounts)));
    }

    private function upsertDiscount(array $state): void
    {
        Discount::withoutGlobalScopes()->updateOrCreate(
            ['slug' => (string) $state['slug']],
            $state
        );
    }
}
