<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\EnumValue;
use Illuminate\Database\Seeder;

final class EnumValueSeeder extends Seeder
{
    public function run(): void
    {
        $enumValues = [
            // Product Status
            [
                'type' => 'product_status',
                'key' => 'active',
                'name' => 'Active',
                'value' => 'active',
                'description' => 'Product is active and available for sale',
                'sort_order' => 1,
                'is_active' => true,
                'is_default' => true,
            ],
            [
                'type' => 'product_status',
                'key' => 'inactive',
                'name' => 'Inactive',
                'value' => 'inactive',
                'description' => 'Product is inactive and not available for sale',
                'sort_order' => 2,
                'is_active' => true,
                'is_default' => false,
            ],
            [
                'type' => 'product_status',
                'key' => 'draft',
                'name' => 'Draft',
                'value' => 'draft',
                'description' => 'Product is in draft status',
                'sort_order' => 3,
                'is_active' => true,
                'is_default' => false,
            ],
            [
                'type' => 'product_status',
                'key' => 'archived',
                'name' => 'Archived',
                'value' => 'archived',
                'description' => 'Product is archived',
                'sort_order' => 4,
                'is_active' => true,
                'is_default' => false,
            ],

            // Order Status
            [
                'type' => 'order_status',
                'key' => 'pending',
                'name' => 'Pending',
                'value' => 'pending',
                'description' => 'Order is pending processing',
                'sort_order' => 1,
                'is_active' => true,
                'is_default' => true,
            ],
            [
                'type' => 'order_status',
                'key' => 'processing',
                'name' => 'Processing',
                'value' => 'processing',
                'description' => 'Order is being processed',
                'sort_order' => 2,
                'is_active' => true,
                'is_default' => false,
            ],
            [
                'type' => 'order_status',
                'key' => 'shipped',
                'name' => 'Shipped',
                'value' => 'shipped',
                'description' => 'Order has been shipped',
                'sort_order' => 3,
                'is_active' => true,
                'is_default' => false,
            ],
            [
                'type' => 'order_status',
                'key' => 'delivered',
                'name' => 'Delivered',
                'value' => 'delivered',
                'description' => 'Order has been delivered',
                'sort_order' => 4,
                'is_active' => true,
                'is_default' => false,
            ],
            [
                'type' => 'order_status',
                'key' => 'cancelled',
                'name' => 'Cancelled',
                'value' => 'cancelled',
                'description' => 'Order has been cancelled',
                'sort_order' => 5,
                'is_active' => true,
                'is_default' => false,
            ],

            // Payment Status
            [
                'type' => 'payment_status',
                'key' => 'pending',
                'name' => 'Pending',
                'value' => 'pending',
                'description' => 'Payment is pending',
                'sort_order' => 1,
                'is_active' => true,
                'is_default' => true,
            ],
            [
                'type' => 'payment_status',
                'key' => 'paid',
                'name' => 'Paid',
                'value' => 'paid',
                'description' => 'Payment has been completed',
                'sort_order' => 2,
                'is_active' => true,
                'is_default' => false,
            ],
            [
                'type' => 'payment_status',
                'key' => 'failed',
                'name' => 'Failed',
                'value' => 'failed',
                'description' => 'Payment has failed',
                'sort_order' => 3,
                'is_active' => true,
                'is_default' => false,
            ],
            [
                'type' => 'payment_status',
                'key' => 'refunded',
                'name' => 'Refunded',
                'value' => 'refunded',
                'description' => 'Payment has been refunded',
                'sort_order' => 4,
                'is_active' => true,
                'is_default' => false,
            ],

            // Shipping Status
            [
                'type' => 'shipping_status',
                'key' => 'pending',
                'name' => 'Pending',
                'value' => 'pending',
                'description' => 'Shipping is pending',
                'sort_order' => 1,
                'is_active' => true,
                'is_default' => true,
            ],
            [
                'type' => 'shipping_status',
                'key' => 'preparing',
                'name' => 'Preparing',
                'value' => 'preparing',
                'description' => 'Order is being prepared for shipping',
                'sort_order' => 2,
                'is_active' => true,
                'is_default' => false,
            ],
            [
                'type' => 'shipping_status',
                'key' => 'shipped',
                'name' => 'Shipped',
                'value' => 'shipped',
                'description' => 'Order has been shipped',
                'sort_order' => 3,
                'is_active' => true,
                'is_default' => false,
            ],
            [
                'type' => 'shipping_status',
                'key' => 'delivered',
                'name' => 'Delivered',
                'value' => 'delivered',
                'description' => 'Order has been delivered',
                'sort_order' => 4,
                'is_active' => true,
                'is_default' => false,
            ],

            // User Roles
            [
                'type' => 'user_role',
                'key' => 'admin',
                'name' => 'Administrator',
                'value' => 'admin',
                'description' => 'System administrator with full access',
                'sort_order' => 1,
                'is_active' => true,
                'is_default' => false,
            ],
            [
                'type' => 'user_role',
                'key' => 'manager',
                'name' => 'Manager',
                'value' => 'manager',
                'description' => 'Manager with limited administrative access',
                'sort_order' => 2,
                'is_active' => true,
                'is_default' => false,
            ],
            [
                'type' => 'user_role',
                'key' => 'customer',
                'name' => 'Customer',
                'value' => 'customer',
                'description' => 'Regular customer',
                'sort_order' => 3,
                'is_active' => true,
                'is_default' => true,
            ],

            // Notification Types
            [
                'type' => 'notification_type',
                'key' => 'email',
                'name' => 'Email',
                'value' => 'email',
                'description' => 'Email notification',
                'sort_order' => 1,
                'is_active' => true,
                'is_default' => true,
            ],
            [
                'type' => 'notification_type',
                'key' => 'sms',
                'name' => 'SMS',
                'value' => 'sms',
                'description' => 'SMS notification',
                'sort_order' => 2,
                'is_active' => true,
                'is_default' => false,
            ],
            [
                'type' => 'notification_type',
                'key' => 'push',
                'name' => 'Push',
                'value' => 'push',
                'description' => 'Push notification',
                'sort_order' => 3,
                'is_active' => true,
                'is_default' => false,
            ],

            // Campaign Status
            [
                'type' => 'campaign_status',
                'key' => 'draft',
                'name' => 'Draft',
                'value' => 'draft',
                'description' => 'Campaign is in draft status',
                'sort_order' => 1,
                'is_active' => true,
                'is_default' => true,
            ],
            [
                'type' => 'campaign_status',
                'key' => 'active',
                'name' => 'Active',
                'value' => 'active',
                'description' => 'Campaign is active',
                'sort_order' => 2,
                'is_active' => true,
                'is_default' => false,
            ],
            [
                'type' => 'campaign_status',
                'key' => 'paused',
                'name' => 'Paused',
                'value' => 'paused',
                'description' => 'Campaign is paused',
                'sort_order' => 3,
                'is_active' => true,
                'is_default' => false,
            ],
            [
                'type' => 'campaign_status',
                'key' => 'completed',
                'name' => 'Completed',
                'value' => 'completed',
                'description' => 'Campaign is completed',
                'sort_order' => 4,
                'is_active' => true,
                'is_default' => false,
            ],

            // Discount Types
            [
                'type' => 'discount_type',
                'key' => 'percentage',
                'name' => 'Percentage',
                'value' => 'percentage',
                'description' => 'Percentage discount',
                'sort_order' => 1,
                'is_active' => true,
                'is_default' => true,
            ],
            [
                'type' => 'discount_type',
                'key' => 'fixed',
                'name' => 'Fixed Amount',
                'value' => 'fixed',
                'description' => 'Fixed amount discount',
                'sort_order' => 2,
                'is_active' => true,
                'is_default' => false,
            ],
            [
                'type' => 'discount_type',
                'key' => 'free_shipping',
                'name' => 'Free Shipping',
                'value' => 'free_shipping',
                'description' => 'Free shipping discount',
                'sort_order' => 3,
                'is_active' => true,
                'is_default' => false,
            ],

            // Inventory Status
            [
                'type' => 'inventory_status',
                'key' => 'in_stock',
                'name' => 'In Stock',
                'value' => 'in_stock',
                'description' => 'Product is in stock',
                'sort_order' => 1,
                'is_active' => true,
                'is_default' => true,
            ],
            [
                'type' => 'inventory_status',
                'key' => 'out_of_stock',
                'name' => 'Out of Stock',
                'value' => 'out_of_stock',
                'description' => 'Product is out of stock',
                'sort_order' => 2,
                'is_active' => true,
                'is_default' => false,
            ],
            [
                'type' => 'inventory_status',
                'key' => 'low_stock',
                'name' => 'Low Stock',
                'value' => 'low_stock',
                'description' => 'Product has low stock',
                'sort_order' => 3,
                'is_active' => true,
                'is_default' => false,
            ],

            // Review Status
            [
                'type' => 'review_status',
                'key' => 'pending',
                'name' => 'Pending',
                'value' => 'pending',
                'description' => 'Review is pending approval',
                'sort_order' => 1,
                'is_active' => true,
                'is_default' => true,
            ],
            [
                'type' => 'review_status',
                'key' => 'approved',
                'name' => 'Approved',
                'value' => 'approved',
                'description' => 'Review has been approved',
                'sort_order' => 2,
                'is_active' => true,
                'is_default' => false,
            ],
            [
                'type' => 'review_status',
                'key' => 'rejected',
                'name' => 'Rejected',
                'value' => 'rejected',
                'description' => 'Review has been rejected',
                'sort_order' => 3,
                'is_active' => true,
                'is_default' => false,
            ],
        ];

        foreach ($enumValues as $enumValue) {
            EnumValue::updateOrCreate(
                [
                    'type' => $enumValue['type'],
                    'key' => $enumValue['key'],
                ],
                $enumValue
            );
        }
    }
}
