<?php

declare(strict_types=1);

namespace Tests\Performance;

use App\Data\Storefront\Home\ProductListItemData;
use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

/**
 * **Feature: performance-update, Property 10: Selective Field Loading**
 * **Validates: Requirements 6.1**
 *
 * Property-based test to ensure product list queries only select fields required by the view/DTO,
 * avoiding unnecessary large text blobs to reduce memory usage and transfer time.
 */
final class SelectiveFieldLoadingTest extends TestCase
{
    use RefreshDatabase;

    /**
     * Test that forProductList scope only selects required fields and excludes large text blobs.
     */
    public function test_for_product_list_scope_selects_only_required_fields(): void
    {
        // Create test product
        Product::factory()->create([
            'name'             => 'Test Product',
            'description'      => str_repeat('Large description text ', 1000), // Large text blob
            'summary'          => str_repeat('Large summary text ', 500), // Large text blob
            'seo_description'  => str_repeat('Large SEO description ', 300), // Large text blob
            'meta_description' => str_repeat('Large meta description ', 200), // Large text blob
            'meta_keywords'    => str_repeat('keyword1,keyword2,keyword3,', 100), // Large text blob
            'request_message'  => str_repeat('Large request message ', 150), // Large text blob
            'metadata'         => json_encode(['large' => str_repeat('data', 1000)]), // Large JSON blob
            'is_visible'       => true,
            'published_at'     => now(),
        ]);

        // Capture the SQL query generated by forProductList scope
        $query = Product::query()->forProductList();
        $sql = $query->toSql();
        $bindings = $query->getBindings();

        // Execute the query to ensure it works
        $products = $query->get();
        $this->assertCount(1, $products);

        // Verify that the query selects only the required fields from ProductListItemData::REQUIRED_PRODUCT_FIELDS
        $requiredFields = ProductListItemData::REQUIRED_PRODUCT_FIELDS;

        foreach ($requiredFields as $field) {
            // Handle both quoted and unquoted field names in SQL
            $quotedField = str_replace('.', '"."', '"' . $field . '"');
            $hasField = str_contains($sql, $field) || str_contains($sql, $quotedField);
            $this->assertTrue($hasField,
                "Query should select required field: {$field}. SQL: {$sql}"
            );
        }

        // Verify that large text blobs are NOT selected
        $excludedFields = [
            'products.description',      // Large text blob
            'products.summary',          // Large text blob
            'products.seo_description',  // Large text blob
            'products.meta_description', // Large text blob
            'products.meta_keywords',    // Large text blob
            'products.request_message',  // Large text blob
            'products.metadata',         // Large JSON blob
        ];

        foreach ($excludedFields as $field) {
            // Handle both quoted and unquoted field names in SQL
            $quotedField = str_replace('.', '"."', '"' . $field . '"');
            $hasField = str_contains($sql, $field) || str_contains($sql, $quotedField);
            $this->assertFalse($hasField,
                "Query should NOT select large text field: {$field}. SQL: {$sql}"
            );
        }

        // Verify the loaded product has the required fields but not the excluded ones
        $product = $products->first();

        // Required fields should be accessible
        $this->assertNotNull($product->id);
        $this->assertNotNull($product->name);
        $this->assertNotNull($product->slug);
        $this->assertNotNull($product->price);

        // Large text fields should not be loaded (will be null or trigger lazy loading)
        $this->assertArrayNotHasKey('description', $product->getAttributes());
        $this->assertArrayNotHasKey('summary', $product->getAttributes());
        $this->assertArrayNotHasKey('seo_description', $product->getAttributes());
        $this->assertArrayNotHasKey('meta_description', $product->getAttributes());
    }

    /**
     * Test that withListRelations scope only loads required relation fields.
     */
    public function test_with_list_relations_scope_loads_minimal_relation_fields(): void
    {
        // Create test data with relations
        $brand = Brand::factory()->create([
            'name'        => 'Test Brand',
            'description' => str_repeat('Large brand description ', 500), // Large text blob
        ]);

        $category = Category::factory()->create([
            'name'        => 'Test Category',
            'description' => str_repeat('Large category description ', 500), // Large text blob
        ]);

        $product = Product::factory()->create([
            'brand_id'     => $brand->id,
            'is_visible'   => true,
            'published_at' => now(),
        ]);

        $product->categories()->attach($category->id);

        // Create translations
        $product->translations()->create([
            'locale'            => 'en',
            'name'              => 'Product Name EN',
            'slug'              => 'product-slug-en',
            'short_description' => 'Short desc EN',
            'description'       => str_repeat('Large translated description ', 1000), // Large text blob
        ]);

        $brand->translations()->create([
            'locale'      => 'en',
            'name'        => 'Brand Name EN',
            'slug'        => 'brand-slug-en',
            'description' => str_repeat('Large translated brand description ', 500), // Large text blob
        ]);

        $category->translations()->create([
            'locale'      => 'en',
            'name'        => 'Category Name EN',
            'slug'        => 'category-slug-en',
            'description' => str_repeat('Large translated category description ', 500), // Large text blob
        ]);

        // Enable query logging to inspect the generated queries
        DB::enableQueryLog();

        // Load product with withListRelations scope
        $loadedProduct = Product::query()
            ->forProductList()
            ->withListRelations()
            ->find($product->id);

        $queries = DB::getQueryLog();
        DB::disableQueryLog();

        $this->assertNotNull($loadedProduct);

        // Verify that brand relation is loaded with minimal fields
        $this->assertTrue($loadedProduct->relationLoaded('brand'));
        if ($loadedProduct->brand) {
            $brandAttributes = $loadedProduct->brand->getAttributes();

            // Should have required fields
            $this->assertArrayHasKey('id', $brandAttributes);
            $this->assertArrayHasKey('name', $brandAttributes);
            $this->assertArrayHasKey('slug', $brandAttributes);

            // Should NOT have large text fields
            $this->assertArrayNotHasKey('description', $brandAttributes);
        }

        // Verify that category relations are loaded with minimal fields
        $this->assertTrue($loadedProduct->relationLoaded('categories'));
        if ($loadedProduct->categories->isNotEmpty()) {
            $categoryAttributes = $loadedProduct->categories->first()->getAttributes();

            // Should have required fields
            $this->assertArrayHasKey('id', $categoryAttributes);
            $this->assertArrayHasKey('name', $categoryAttributes);
            $this->assertArrayHasKey('slug', $categoryAttributes);

            // Should NOT have large text fields
            $this->assertArrayNotHasKey('description', $categoryAttributes);
        }

        // Verify that translation relations are loaded with minimal fields
        $this->assertTrue($loadedProduct->relationLoaded('translations'));
        if ($loadedProduct->translations->isNotEmpty()) {
            $translationAttributes = $loadedProduct->translations->first()->getAttributes();

            // Should have required fields
            $this->assertArrayHasKey('product_id', $translationAttributes);
            $this->assertArrayHasKey('locale', $translationAttributes);
            $this->assertArrayHasKey('name', $translationAttributes);
            $this->assertArrayHasKey('slug', $translationAttributes);
            $this->assertArrayHasKey('short_description', $translationAttributes);

            // Should NOT have large text fields
            $this->assertArrayNotHasKey('description', $translationAttributes);
        }
    }

    /**
     * Test that ProductListItemData can be created from optimally loaded products without lazy loading.
     */
    public function test_product_list_item_data_works_with_selective_field_loading(): void
    {
        // Set application locale to ensure consistent translation behavior
        app()->setLocale('en');

        // Create test data
        $brand = Brand::factory()->create(['name' => 'Test Brand']);
        $category = Category::factory()->create(['name' => 'Test Category']);

        $product = Product::factory()->create([
            'brand_id'          => $brand->id,
            'name'              => 'Test Product',
            'short_description' => 'Short description',
            'description'       => str_repeat('Large description ', 1000), // Large text blob
            'is_visible'        => true,
            'published_at'      => now(),
        ]);

        $product->categories()->attach($category->id);

        // Create translations
        $product->translations()->create([
            'locale'            => 'en',
            'name'              => 'Product Name EN',
            'slug'              => 'product-slug-en',
            'short_description' => 'Short desc EN',
        ]);

        $brand->translations()->create([
            'locale' => 'en',
            'name'   => 'Brand Name EN',
            'slug'   => 'brand-slug-en',
        ]);

        $category->translations()->create([
            'locale' => 'en',
            'name'   => 'Category Name EN',
            'slug'   => 'category-slug-en',
        ]);

        // Load product with selective field loading and required aggregates
        $loadedProduct = Product::query()
            ->forProductList()
            ->withListRelations()
            ->find($product->id);

        $this->assertNotNull($loadedProduct);

        // Verify translations are properly loaded
        $this->assertTrue($loadedProduct->relationLoaded('translations'));
        $this->assertNotEmpty($loadedProduct->translations);

        // Enable query logging to detect any lazy loading
        DB::enableQueryLog();

        // Create ProductListItemData - this should not trigger any additional queries
        $dto = ProductListItemData::fromModel($loadedProduct, 'en');

        $queries = DB::getQueryLog();
        DB::disableQueryLog();

        // Filter out schema introspection queries (these are not lazy loading)
        $actualQueries = array_filter($queries, function ($query) {
            $sql = strtolower($query['query']);

            return ! str_contains($sql, 'pragma_table_xinfo') &&
                   ! str_contains($sql, 'sqlite_master') &&
                   ! str_contains($sql, 'information_schema');
        });

        // Assert no actual lazy loading queries were triggered during DTO creation
        $this->assertEmpty($actualQueries,
            'ProductListItemData::fromModel triggered lazy loading queries: ' . json_encode($actualQueries)
        );

        // Verify DTO has expected data - use the translated values if available, fallback to base values
        $this->assertEquals($product->id, $dto->id);

        // Check if translation was used or fallback to base value
        $expectedName = $loadedProduct->trans('name', 'en') ?? $product->name;
        $this->assertEquals($expectedName, $dto->name);

        $expectedBrandName = $loadedProduct->brand?->trans('name', 'en') ?? $brand->name;
        $this->assertEquals($expectedBrandName, $dto->brandName);

        // For categories, check if any translated name is present
        $this->assertNotEmpty($dto->categoryLabels);

        $expectedShortDesc = $loadedProduct->trans('short_description', 'en') ?? $product->short_description;
        $this->assertEquals($expectedShortDesc, $dto->shortDescription);
    }

    /**
     * Test that multiple product list queries consistently use selective field loading.
     */
    public function test_multiple_product_list_queries_use_selective_loading(): void
    {
        // Create test data
        $brand = Brand::factory()->create();
        $category = Category::factory()->create(['is_visible' => true]);

        $products = Product::factory()
            ->count(10)
            ->create([
                'brand_id'     => $brand->id,
                'is_visible'   => true,
                'is_featured'  => true,
                'published_at' => now()->subDay(),
                'description'  => str_repeat('Large description text ', 1000), // Large text blob
            ]);

        foreach ($products as $product) {
            $product->categories()->attach($category->id);
        }

        // Test different query patterns that should all use selective field loading
        $queryPatterns = [
            // Basic product list query
            fn () => Product::query()->forProductList()->withListRelations()->limit(5)->get(),

            // Category products query
            fn () => $category->products()->forProductList()->withListRelations()->limit(5)->get(),

            // Brand products query
            fn () => $brand->products()->forProductList()->withListRelations()->limit(5)->get(),

            // Featured products query
            fn () => Product::query()->forProductList()->withListRelations()->where('is_featured', true)->limit(5)->get(),
        ];

        foreach ($queryPatterns as $index => $queryCallback) {
            // Enable query logging
            DB::enableQueryLog();

            // Execute the query
            $results = $queryCallback();

            $queries = DB::getQueryLog();
            DB::disableQueryLog();

            $this->assertNotEmpty($results, "Query pattern {$index} should return results");

            // Check that the main product query uses selective field loading
            $productQuery = collect($queries)->first(fn ($query) => str_contains($query['query'], 'select') &&
                str_contains($query['query'], 'products')
            );

            if ($productQuery) {
                $sql = $productQuery['query'];

                // Should select required fields (handle quoted field names)
                $this->assertTrue(
                    str_contains($sql, 'products.id') || str_contains($sql, '"products"."id"'),
                    "Query pattern {$index} should select products.id. SQL: {$sql}"
                );
                $this->assertTrue(
                    str_contains($sql, 'products.name') || str_contains($sql, '"products"."name"'),
                    "Query pattern {$index} should select products.name. SQL: {$sql}"
                );
                $this->assertTrue(
                    str_contains($sql, 'products.price') || str_contains($sql, '"products"."price"'),
                    "Query pattern {$index} should select products.price. SQL: {$sql}"
                );

                // Should NOT select large text blobs (handle quoted field names)
                $this->assertFalse(
                    str_contains($sql, 'products.description') || str_contains($sql, '"products"."description"'),
                    "Query pattern {$index} should not select description field. SQL: {$sql}"
                );
                $this->assertFalse(
                    str_contains($sql, 'products.summary') || str_contains($sql, '"products"."summary"'),
                    "Query pattern {$index} should not select summary field. SQL: {$sql}"
                );
            }

            // Verify that each loaded product doesn't have large text fields in attributes
            foreach ($results as $product) {
                $attributes = $product->getAttributes();
                $this->assertArrayNotHasKey('description', $attributes,
                    "Product should not have description loaded in query pattern {$index}"
                );
                $this->assertArrayNotHasKey('summary', $attributes,
                    "Product should not have summary loaded in query pattern {$index}"
                );
            }
        }
    }

    /**
     * Test that selective field loading reduces memory usage compared to loading all fields.
     */
    public function test_selective_field_loading_reduces_memory_usage(): void
    {
        // Create products with large text content
        $products = Product::factory()
            ->count(50)
            ->create([
                'description'      => str_repeat('Large description text ', 2000), // ~40KB per product
                'summary'          => str_repeat('Large summary text ', 1000), // ~20KB per product
                'seo_description'  => str_repeat('Large SEO description ', 500), // ~10KB per product
                'meta_description' => str_repeat('Large meta description ', 300), // ~6KB per product
                'is_visible'       => true,
                'published_at'     => now(),
            ]);

        // Measure memory usage with selective field loading
        $memoryBefore = memory_get_usage(true);
        $selectiveProducts = Product::query()->forProductList()->get();
        $memoryAfterSelective = memory_get_usage(true);
        $selectiveMemoryUsage = $memoryAfterSelective - $memoryBefore;

        // Clear memory
        unset($selectiveProducts);
        gc_collect_cycles();

        // Measure memory usage with full field loading
        $memoryBefore = memory_get_usage(true);
        $fullProducts = Product::query()->select('*')->get();
        $memoryAfterFull = memory_get_usage(true);
        $fullMemoryUsage = $memoryAfterFull - $memoryBefore;

        // Selective loading should use significantly less memory
        $memoryReduction = ($fullMemoryUsage - $selectiveMemoryUsage) / $fullMemoryUsage;

        $this->assertGreaterThan(0.3, $memoryReduction,
            'Selective field loading should reduce memory usage by at least 30%. ' .
            "Full: {$fullMemoryUsage} bytes, Selective: {$selectiveMemoryUsage} bytes, " .
            'Reduction: ' . round($memoryReduction * 100, 2) . '%'
        );

        // Verify that selective loading still returns valid products
        $this->assertCount(50, Product::query()->forProductList()->get());
    }
}
