<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ ucfirst($export->type->value) }} export</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #111827; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
        th, td { border: 1px solid #e5e7eb; padding: 8px; text-align: left; }
        th { background-color: #f3f4f6; font-weight: bold; }
        tfoot td { font-weight: bold; background-color: #f9fafb; }
        h1 { font-size: 18px; margin-bottom: 8px; }
        .meta { margin-bottom: 12px; }
    </style>
</head>
<body>
    <h1>{{ ucfirst($export->type->value) }} export</h1>
    <div class="meta">
        <div>{{ __('Generated at: :date', ['date' => now()->timezone($export->timezone)->toDayDateTimeString()]) }}</div>
        <div>{{ __('Generated by export #:id', ['id' => $export->getKey()]) }}</div>
        <div>{{ __('Total rows: :count', ['count' => number_format($export->total_rows)]) }}</div>
    </div>
    @php
        $numericTypes = ['currency', 'integer'];
        $totals = [];
        foreach ($columns as $column) {
            if (in_array($column['type'], $numericTypes, true)) {
                $label = $column['label'];
                $totals[$label] = collect($rows)->sum(function ($row) use ($label, $column) {
                    $value = $row[$label] ?? 0;
                    return is_numeric($value) ? (float) $value : 0.0;
                });
            }
        }
    @endphp
    <table>
        <thead>
            <tr>
                @foreach ($columns as $column)
                    <th>{{ $column['label'] }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    @foreach ($columns as $column)
                        <td>{{ $row[$column['label']] ?? '' }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($columns) }}">{{ __('No data available for this export.') }}</td>
                </tr>
            @endforelse
        </tbody>
        @if ($totals !== [])
            <tfoot>
                <tr>
                    @foreach ($columns as $column)
                        @php $label = $column['label']; @endphp
                        <td>
                            @if (array_key_exists($label, $totals))
                                {{ $totals[$label] }}
                            @endif
                        </td>
                    @endforeach
                </tr>
            </tfoot>
        @endif
    </table>
</body>
</html>
