<?php

declare(strict_types=1);

return [
    'title' => 'Reports',
    'description' => 'View and download our reports',

    // Filters
    'filters' => [
        'search' => 'Search',
        'search_placeholder' => 'Search reports...',
        'type' => 'Type',
        'category' => 'Category',
        'sort' => 'Sort',
        'all_types' => 'All Types',
        'all_categories' => 'All Categories',
        'sort_by_date' => 'By Date',
        'sort_by_name' => 'By Name',
        'sort_by_views' => 'By Views',
        'sort_by_downloads' => 'By Downloads',
        'apply' => 'Apply',
        'clear' => 'Clear',
    ],

    // Actions
    'actions' => [
        'view' => 'View',
        'download' => 'Download',
        'generate' => 'Generate',
        'print' => 'Print',
        'title' => 'Actions',
    ],

    // Stats
    'stats' => [
        'views' => 'Views',
        'downloads' => 'Downloads',
        'created' => 'Created',
        'last_generated' => 'Last Generated',
    ],

    // Content
    'content' => [
        'title' => 'Content',
    ],

    // Info
    'info' => [
        'title' => 'Information',
        'type' => 'Type',
        'category' => 'Category',
        'date_range' => 'Date Range',
        'created' => 'Created',
        'last_generated' => 'Last Generated',
        'generated_by' => 'Generated By',
    ],

    // Related
    'related' => [
        'title' => 'Related Reports',
    ],

    // Empty state
    'empty' => [
        'title' => 'No Reports Found',
        'description' => 'No reports found matching your search criteria.',
    ],

    // Messages
    'messages' => [
        'access_denied' => 'You do not have permission to view this report.',
        'generated_successfully' => 'Report generated successfully.',
    ],

    // PDF
    'pdf' => [
        'generated_on' => 'Generated On',
        'type' => 'Type',
        'category' => 'Category',
        'date_range' => 'Date Range',
        'period' => 'Period',
        'generated_by' => 'Generated By',
        'created' => 'Created',
        'description' => 'Description',
        'content' => 'Content',
        'filters' => 'Filters',
        'views' => 'Views',
        'downloads' => 'Downloads',
        'status' => 'Status',
        'active' => 'Active',
        'inactive' => 'Inactive',
        'footer' => 'Report: :name | Generated: :date',
    ],
];

