<?php

declare(strict_types=1);

return [
    'guards' => [
        'admin',
        'web',
        'sanctum',
    ],

    'testing' => [
        'skip_checks' => true,
    ],

    'abilities' => [
        'panel' => [
            'access' => 'panel.access.admin',
        ],
        'products' => [
            'viewAny' => 'view_products',
            'view'    => 'view_products',
            'create'  => 'create_products',
            'update'  => 'edit_products',
            'delete'  => 'delete_products',
        ],
        'categories' => [
            'viewAny' => 'categories.viewAny',
            'view'    => 'categories.view',
            'create'  => 'categories.create',
            'update'  => 'categories.update',
            'delete'  => 'categories.delete',
        ],
        'brands' => [
            'viewAny' => 'brands.viewAny',
            'view'    => 'brands.view',
            'create'  => 'brands.create',
            'update'  => 'brands.update',
            'delete'  => 'brands.delete',
        ],
        'orders' => [
            'viewAny' => 'orders.viewAny',
            'view'    => 'orders.view',
            'create'  => 'orders.create',
            'update'  => 'orders.update',
            'delete'  => 'orders.delete',
        ],
        'users' => [
            'viewAny' => 'users.viewAny',
            'view'    => 'users.view',
            'create'  => 'users.create',
            'update'  => 'users.update',
            'delete'  => 'users.delete',
        ],
        'roles' => [
            'viewAny'        => 'roles.viewAny',
            'view'           => 'roles.view',
            'create'         => 'roles.create',
            'update'         => 'roles.update',
            'delete'         => 'roles.delete',
            'restore'        => 'roles.update',
            'forceDelete'    => 'roles.delete',
            'forceDeleteAny' => 'roles.delete',
            'restoreAny'     => 'roles.update',
            'replicate'      => 'roles.create',
            'reorder'        => 'roles.update',
        ],
        'audit_logs' => [
            'viewAny' => 'audit_logs.viewAny',
        ],
        'product_histories' => [
            'viewAny' => 'product_histories.viewAny',
            'view'    => 'product_histories.view',
            'create'  => 'product_histories.create',
            'export'  => 'product_histories.export',
        ],
        // Gatekeeping for discount rule management and diagnostic helpers.
        'discount_conditions' => [
            'viewAny' => 'discount_conditions.viewAny',
            'view'    => 'discount_conditions.view',
        ],
        'system_settings' => [
            'viewAny' => 'system_settings.viewAny',
            'view'    => 'system_settings.view',
            'create'  => 'system_settings.create',
            'update'  => 'system_settings.update',
            'delete'  => 'system_settings.delete',
        ],
        'notifications' => [
            'viewAny'     => 'notifications.viewAny',
            'view'        => 'notifications.view',
            'create'      => 'notifications.create',
            'update'      => 'notifications.update',
            'delete'      => 'notifications.delete',
            'markAsRead'  => 'notifications.update',
            'markAsUnread'=> 'notifications.update',
            'bulkUpdate'  => 'notifications.update',
            'bulkDelete'  => 'notifications.delete',
            'duplicate'   => 'notifications.create',
        ],
        'product_requests' => [
            'viewAny' => 'product_requests.viewAny',
            'view'    => 'product_requests.view',
            'create'  => 'product_requests.create',
            'update'  => 'product_requests.update',
            'delete'  => 'product_requests.delete',
            'respond' => 'product_requests.respond',
        ],
    ],

    'roles' => [
        'super_admin' => ['*'],
        'admin'       => [
            'panel.access.admin',
            'view_products', 'create_products', 'edit_products', 'delete_products',
            'categories.viewAny', 'categories.view', 'categories.create', 'categories.update', 'categories.delete',
            'brands.viewAny', 'brands.view', 'brands.create', 'brands.update', 'brands.delete',
            'orders.viewAny', 'orders.view', 'orders.create', 'orders.update', 'orders.delete',
            'users.viewAny', 'users.view', 'users.create', 'users.update', 'users.delete',
            'roles.viewAny', 'roles.view', 'roles.create', 'roles.update', 'roles.delete',
            'audit_logs.viewAny',
            'product_histories.viewAny', 'product_histories.view', 'product_histories.create', 'product_histories.export',
            'discount_conditions.viewAny', 'discount_conditions.view',
            'system_settings.viewAny', 'system_settings.view', 'system_settings.create', 'system_settings.update', 'system_settings.delete',
            'notifications.viewAny', 'notifications.view', 'notifications.create', 'notifications.update', 'notifications.delete',
            'product_requests.viewAny', 'product_requests.view', 'product_requests.create', 'product_requests.update', 'product_requests.delete', 'product_requests.respond',
        ],
        'administrator' => [
            'panel.access.admin',
            'view_products', 'create_products', 'edit_products', 'delete_products',
            'categories.viewAny', 'categories.view', 'categories.create', 'categories.update', 'categories.delete',
            'brands.viewAny', 'brands.view', 'brands.create', 'brands.update', 'brands.delete',
            'orders.viewAny', 'orders.view', 'orders.create', 'orders.update', 'orders.delete',
            'users.viewAny', 'users.view', 'users.create', 'users.update', 'users.delete',
            'roles.viewAny', 'roles.view', 'roles.create', 'roles.update', 'roles.delete',
            'audit_logs.viewAny',
            'product_histories.viewAny', 'product_histories.view', 'product_histories.create', 'product_histories.export',
            'discount_conditions.viewAny', 'discount_conditions.view',
            'system_settings.viewAny', 'system_settings.view', 'system_settings.create', 'system_settings.update', 'system_settings.delete',
            'notifications.viewAny', 'notifications.view', 'notifications.create', 'notifications.update', 'notifications.delete',
            'product_requests.viewAny', 'product_requests.view', 'product_requests.create', 'product_requests.update', 'product_requests.delete', 'product_requests.respond',
        ],
        'manager' => [
            'panel.access.admin',
            'view_products', 'create_products', 'edit_products',
            'categories.viewAny', 'categories.view', 'categories.create', 'categories.update',
            'brands.viewAny', 'brands.view', 'brands.update',
            'orders.viewAny', 'orders.view', 'orders.update',
            'users.viewAny', 'users.view',
            'discount_conditions.viewAny', 'discount_conditions.view',
            'notifications.viewAny', 'notifications.view', 'notifications.update',
            'product_requests.viewAny', 'product_requests.view', 'product_requests.update',
        ],
        'editor' => [
            'panel.access.admin',
            'view_products', 'edit_products',
            'categories.viewAny', 'categories.view', 'categories.update',
            'brands.viewAny', 'brands.view', 'brands.update',
            'discount_conditions.viewAny', 'discount_conditions.view',
            'notifications.viewAny', 'notifications.view',
        ],
        'support' => [
            'panel.access.admin',
            'orders.viewAny', 'orders.view', 'orders.update',
            'users.viewAny', 'users.view', 'users.update',
            'notifications.viewAny', 'notifications.view', 'notifications.update',
        ],
        'viewer' => [
            'panel.access.admin',
            'view_products',
            'categories.viewAny', 'categories.view',
            'brands.viewAny', 'brands.view',
            'orders.viewAny', 'orders.view',
            'discount_conditions.viewAny', 'discount_conditions.view',
            'notifications.viewAny', 'notifications.view',
        ],
        'user' => [],
    ],
];
