echo "husky - DEPRECATED

Please remove the following two lines from $0:

#!/usr/bin/env sh
# Compatibility shim generated by scripts/ensure-husky-shim.mjs.
# It simply forwards to the maintained Husky helper in '_/h' so legacy hooks keep running.
. "$(dirname -- "$0")/h"

