<?php

require_once 'vendor/autoload.php';

use Illuminate\Database\Capsule\Manager as Capsule;
use Illuminate\Events\Dispatcher;
use Illuminate\Container\Container;

$capsule = new Capsule;

$capsule->addConnection([
    'driver' => 'sqlite',
    'database' => __DIR__ . '/database/database.sqlite',
    'prefix' => '',
]);

$capsule->setEventDispatcher(new Dispatcher(new Container));
$capsule->setAsGlobal();
$capsule->bootEloquent();

echo "=== Complete System Settings Seeder ===\n\n";

// Get category IDs
$categoryIds = Capsule::table('system_setting_categories')->pluck('id', 'slug');

// Comprehensive settings data
$settings = [
    // General Settings
    [
        'category_id' => $categoryIds['general'],
        'key' => 'app.description',
        'name' => 'Application Description',
        'value' => 'Professional construction materials e-commerce platform',
        'type' => 'text',
        'group' => 'general',
        'description' => 'Brief description of your application',
        'help_text' => 'Used for SEO meta descriptions and social media sharing',
        'is_public' => true,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['general'],
        'key' => 'app.timezone',
        'name' => 'Timezone',
        'value' => 'Europe/Vilnius',
        'type' => 'select',
        'group' => 'general',
        'description' => 'Default timezone for the application',
        'help_text' => 'All dates and times will be displayed in this timezone',
        'is_public' => false,
        'is_required' => true,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'options' => json_encode([
            'Europe/Vilnius' => 'Vilnius (GMT+2)',
            'Europe/London' => 'London (GMT+0)',
            'Europe/Berlin' => 'Berlin (GMT+1)',
            'America/New_York' => 'New York (GMT-5)',
        ]),
        'sort_order' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['general'],
        'key' => 'app.language',
        'name' => 'Default Language',
        'value' => 'lt',
        'type' => 'select',
        'group' => 'general',
        'description' => 'Default language for the application',
        'help_text' => 'This will be the default language for new users',
        'is_public' => true,
        'is_required' => true,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'options' => json_encode([
            'lt' => 'Lietuvių',
            'en' => 'English',
            'de' => 'Deutsch',
        ]),
        'sort_order' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['general'],
        'key' => 'app.maintenance_mode',
        'name' => 'Maintenance Mode',
        'value' => json_encode(false),
        'type' => 'boolean',
        'group' => 'general',
        'description' => 'Enable maintenance mode',
        'help_text' => 'When enabled, only administrators can access the site',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 5,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['general'],
        'key' => 'app.debug_mode',
        'name' => 'Debug Mode',
        'value' => json_encode(false),
        'type' => 'boolean',
        'group' => 'general',
        'description' => 'Enable debug mode',
        'help_text' => 'Shows detailed error information (disable in production)',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 6,
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // E-commerce Settings
    [
        'category_id' => $categoryIds['ecommerce'],
        'key' => 'ecommerce.min_order_amount',
        'name' => 'Minimum Order Amount',
        'value' => '50.0',
        'type' => 'number',
        'group' => 'ecommerce',
        'description' => 'Minimum order amount for checkout',
        'help_text' => 'Customers must reach this amount to complete their order',
        'is_public' => true,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['ecommerce'],
        'key' => 'ecommerce.free_shipping_threshold',
        'name' => 'Free Shipping Threshold',
        'value' => '100.0',
        'type' => 'number',
        'group' => 'ecommerce',
        'description' => 'Order amount for free shipping',
        'help_text' => 'Orders above this amount will have free shipping',
        'is_public' => true,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['ecommerce'],
        'key' => 'ecommerce.inventory_tracking',
        'name' => 'Inventory Tracking',
        'value' => json_encode(true),
        'type' => 'boolean',
        'group' => 'ecommerce',
        'description' => 'Enable inventory tracking',
        'help_text' => 'Track product stock levels and prevent overselling',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['ecommerce'],
        'key' => 'ecommerce.low_stock_threshold',
        'name' => 'Low Stock Threshold',
        'value' => '10',
        'type' => 'number',
        'group' => 'ecommerce',
        'description' => 'Stock level to trigger low stock alerts',
        'help_text' => 'Products with stock below this number will trigger alerts',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 5,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['ecommerce'],
        'key' => 'ecommerce.allow_guest_checkout',
        'name' => 'Allow Guest Checkout',
        'value' => json_encode(true),
        'type' => 'boolean',
        'group' => 'ecommerce',
        'description' => 'Allow customers to checkout without registration',
        'help_text' => 'When disabled, customers must create an account to purchase',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 6,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['ecommerce'],
        'key' => 'ecommerce.product_reviews',
        'name' => 'Enable Product Reviews',
        'value' => json_encode(true),
        'type' => 'boolean',
        'group' => 'ecommerce',
        'description' => 'Allow customers to review products',
        'help_text' => 'Enable or disable the product review system',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 7,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['ecommerce'],
        'key' => 'ecommerce.wishlist_enabled',
        'name' => 'Enable Wishlist',
        'value' => json_encode(true),
        'type' => 'boolean',
        'group' => 'ecommerce',
        'description' => 'Enable customer wishlist functionality',
        'help_text' => 'Allow customers to save products to their wishlist',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 8,
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Email Settings
    [
        'category_id' => $categoryIds['email'],
        'key' => 'mail.from_name',
        'name' => 'From Name',
        'value' => 'Statybos E-commerce',
        'type' => 'string',
        'group' => 'email',
        'description' => 'Default sender name',
        'help_text' => 'This name will be displayed as the sender for all system emails',
        'is_public' => false,
        'is_required' => true,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['email'],
        'key' => 'mail.support_email',
        'name' => 'Support Email',
        'value' => 'support@statybaecommerse.prus.dev',
        'type' => 'string',
        'group' => 'email',
        'description' => 'Customer support email address',
        'help_text' => 'This email will be used for customer support inquiries',
        'is_public' => true,
        'is_required' => true,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['email'],
        'key' => 'mail.admin_email',
        'name' => 'Admin Email',
        'value' => 'admin@statybaecommerse.prus.dev',
        'type' => 'string',
        'group' => 'email',
        'description' => 'Administrator email address',
        'help_text' => 'This email will receive system notifications and alerts',
        'is_public' => false,
        'is_required' => true,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['email'],
        'key' => 'mail.queue_emails',
        'name' => 'Queue Emails',
        'value' => json_encode(true),
        'type' => 'boolean',
        'group' => 'email',
        'description' => 'Queue emails for background processing',
        'help_text' => 'When enabled, emails will be queued for better performance',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 5,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['email'],
        'key' => 'mail.rate_limit',
        'name' => 'Email Rate Limit',
        'value' => '100',
        'type' => 'number',
        'group' => 'email',
        'description' => 'Maximum emails per hour',
        'help_text' => 'Limit the number of emails sent per hour to prevent spam',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 6,
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Payment Settings
    [
        'category_id' => $categoryIds['payment'],
        'key' => 'payment.default_method',
        'name' => 'Default Payment Method',
        'value' => 'bank_transfer',
        'type' => 'select',
        'group' => 'payment',
        'description' => 'Default payment method for orders',
        'help_text' => 'This will be pre-selected during checkout',
        'is_public' => true,
        'is_required' => true,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'options' => json_encode([
            'bank_transfer' => 'Bank Transfer',
            'credit_card' => 'Credit Card',
            'paypal' => 'PayPal',
            'cash_on_delivery' => 'Cash on Delivery',
        ]),
        'sort_order' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['payment'],
        'key' => 'payment.auto_approve_orders',
        'name' => 'Auto Approve Orders',
        'value' => json_encode(false),
        'type' => 'boolean',
        'group' => 'payment',
        'description' => 'Automatically approve orders after payment',
        'help_text' => 'When enabled, orders will be automatically approved after successful payment',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['payment'],
        'key' => 'payment.payment_timeout',
        'name' => 'Payment Timeout (minutes)',
        'value' => '30',
        'type' => 'number',
        'group' => 'payment',
        'description' => 'Time limit for payment completion',
        'help_text' => 'Orders will be cancelled if payment is not completed within this time',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Shipping Settings
    [
        'category_id' => $categoryIds['shipping'],
        'key' => 'shipping.default_method',
        'name' => 'Default Shipping Method',
        'value' => 'standard',
        'type' => 'select',
        'group' => 'shipping',
        'description' => 'Default shipping method for orders',
        'help_text' => 'This will be pre-selected during checkout',
        'is_public' => true,
        'is_required' => true,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'options' => json_encode([
            'standard' => 'Standard Shipping',
            'express' => 'Express Shipping',
            'pickup' => 'Store Pickup',
        ]),
        'sort_order' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['shipping'],
        'key' => 'shipping.default_cost',
        'name' => 'Default Shipping Cost',
        'value' => '5.99',
        'type' => 'number',
        'group' => 'shipping',
        'description' => 'Default shipping cost in EUR',
        'help_text' => 'This cost will be applied when no specific shipping method is selected',
        'is_public' => true,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['shipping'],
        'key' => 'shipping.estimated_delivery_days',
        'name' => 'Estimated Delivery Days',
        'value' => '3',
        'type' => 'number',
        'group' => 'shipping',
        'description' => 'Estimated delivery time in days',
        'help_text' => 'This will be shown to customers during checkout',
        'is_public' => true,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // SEO Settings
    [
        'category_id' => $categoryIds['seo'],
        'key' => 'seo.meta_title',
        'name' => 'Default Meta Title',
        'value' => 'Statybos E-commerce - Professional Construction Materials',
        'type' => 'string',
        'group' => 'seo',
        'description' => 'Default meta title for pages',
        'help_text' => 'This will be used when no specific meta title is set',
        'is_public' => true,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['seo'],
        'key' => 'seo.meta_description',
        'name' => 'Default Meta Description',
        'value' => 'Professional construction materials and tools for your building projects. Quality products, competitive prices, fast delivery.',
        'type' => 'text',
        'group' => 'seo',
        'description' => 'Default meta description for pages',
        'help_text' => 'This will be used when no specific meta description is set',
        'is_public' => true,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['seo'],
        'key' => 'seo.meta_keywords',
        'name' => 'Default Meta Keywords',
        'value' => 'construction materials, building supplies, tools, statyba, statybos medžiagos',
        'type' => 'string',
        'group' => 'seo',
        'description' => 'Default meta keywords for pages',
        'help_text' => 'Comma-separated keywords for SEO',
        'is_public' => true,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['seo'],
        'key' => 'seo.google_analytics_id',
        'name' => 'Google Analytics ID',
        'value' => '',
        'type' => 'string',
        'group' => 'seo',
        'description' => 'Google Analytics tracking ID',
        'help_text' => 'Enter your Google Analytics tracking ID (e.g., GA-XXXXXXXXX)',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['seo'],
        'key' => 'seo.google_search_console',
        'name' => 'Google Search Console Verification',
        'value' => '',
        'type' => 'string',
        'group' => 'seo',
        'description' => 'Google Search Console verification code',
        'help_text' => 'Enter your Google Search Console verification meta tag content',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 5,
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Security Settings
    [
        'category_id' => $categoryIds['security'],
        'key' => 'security.password_min_length',
        'name' => 'Minimum Password Length',
        'value' => '8',
        'type' => 'number',
        'group' => 'security',
        'description' => 'Minimum password length requirement',
        'help_text' => 'Users must create passwords with at least this many characters',
        'is_public' => false,
        'is_required' => true,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['security'],
        'key' => 'security.password_require_special',
        'name' => 'Require Special Characters',
        'value' => json_encode(true),
        'type' => 'boolean',
        'group' => 'security',
        'description' => 'Require special characters in passwords',
        'help_text' => 'Passwords must contain at least one special character',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['security'],
        'key' => 'security.session_timeout',
        'name' => 'Session Timeout (minutes)',
        'value' => '120',
        'type' => 'number',
        'group' => 'security',
        'description' => 'User session timeout in minutes',
        'help_text' => 'Users will be logged out after this period of inactivity',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['security'],
        'key' => 'security.max_login_attempts',
        'name' => 'Max Login Attempts',
        'value' => '5',
        'type' => 'number',
        'group' => 'security',
        'description' => 'Maximum failed login attempts before lockout',
        'help_text' => 'Account will be locked after this many failed attempts',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['security'],
        'key' => 'security.two_factor_auth',
        'name' => 'Enable Two-Factor Authentication',
        'value' => json_encode(false),
        'type' => 'boolean',
        'group' => 'security',
        'description' => 'Enable two-factor authentication for admin users',
        'help_text' => 'Admin users will be required to use 2FA',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 5,
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // API Settings
    [
        'category_id' => $categoryIds['api'],
        'key' => 'api.rate_limit',
        'name' => 'API Rate Limit',
        'value' => '1000',
        'type' => 'number',
        'group' => 'api',
        'description' => 'API requests per hour limit',
        'help_text' => 'Maximum number of API requests allowed per hour',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['api'],
        'key' => 'api.api_key_length',
        'name' => 'API Key Length',
        'value' => '32',
        'type' => 'number',
        'group' => 'api',
        'description' => 'Length of generated API keys',
        'help_text' => 'API keys will be generated with this length',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['api'],
        'key' => 'api.enable_api',
        'name' => 'Enable API',
        'value' => json_encode(true),
        'type' => 'boolean',
        'group' => 'api',
        'description' => 'Enable API access',
        'help_text' => 'Allow external applications to access the API',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Appearance Settings
    [
        'category_id' => $categoryIds['appearance'],
        'key' => 'appearance.primary_color',
        'name' => 'Primary Color',
        'value' => '#3B82F6',
        'type' => 'color',
        'group' => 'appearance',
        'description' => 'Primary brand color',
        'help_text' => 'This color will be used throughout the application',
        'is_public' => true,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['appearance'],
        'key' => 'appearance.secondary_color',
        'name' => 'Secondary Color',
        'value' => '#6B7280',
        'type' => 'color',
        'group' => 'appearance',
        'description' => 'Secondary brand color',
        'help_text' => 'This color will be used for secondary elements',
        'is_public' => true,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['appearance'],
        'key' => 'appearance.logo_url',
        'name' => 'Logo URL',
        'value' => '',
        'type' => 'string',
        'group' => 'appearance',
        'description' => 'URL to the application logo',
        'help_text' => 'This logo will be displayed in the header and emails',
        'is_public' => true,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['appearance'],
        'key' => 'appearance.favicon_url',
        'name' => 'Favicon URL',
        'value' => '',
        'type' => 'string',
        'group' => 'appearance',
        'description' => 'URL to the favicon',
        'help_text' => 'This icon will be displayed in browser tabs',
        'is_public' => true,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Notification Settings
    [
        'category_id' => $categoryIds['notifications'],
        'key' => 'notifications.email_notifications',
        'name' => 'Enable Email Notifications',
        'value' => json_encode(true),
        'type' => 'boolean',
        'group' => 'notifications',
        'description' => 'Enable email notifications',
        'help_text' => 'Send email notifications for important events',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['notifications'],
        'key' => 'notifications.sms_notifications',
        'name' => 'Enable SMS Notifications',
        'value' => json_encode(false),
        'type' => 'boolean',
        'group' => 'notifications',
        'description' => 'Enable SMS notifications',
        'help_text' => 'Send SMS notifications for important events',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => $categoryIds['notifications'],
        'key' => 'notifications.push_notifications',
        'name' => 'Enable Push Notifications',
        'value' => json_encode(true),
        'type' => 'boolean',
        'group' => 'notifications',
        'description' => 'Enable browser push notifications',
        'help_text' => 'Send push notifications to users browsers',
        'is_public' => false,
        'is_required' => false,
        'is_encrypted' => false,
        'is_readonly' => false,
        'is_active' => true,
        'sort_order' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
];

// Insert all settings
foreach ($settings as $setting) {
    Capsule::table('system_settings')->insert($setting);
}

echo "✅ Added " . count($settings) . " additional settings\n";

// Show final statistics
$totalSettings = Capsule::table('system_settings')->count();
$totalCategories = Capsule::table('system_setting_categories')->count();

echo "\n=== Final Statistics ===\n";
echo "Total Categories: {$totalCategories}\n";
echo "Total Settings: {$totalSettings}\n";

// Show settings by category
echo "\nSettings by Category:\n";
$categoryStats = Capsule::table('system_settings')
    ->join('system_setting_categories', 'system_settings.category_id', '=', 'system_setting_categories.id')
    ->selectRaw('system_setting_categories.name, count(*) as count')
    ->groupBy('system_setting_categories.name')
    ->orderBy('count', 'desc')
    ->get();

foreach ($categoryStats as $stat) {
    echo "  - {$stat->name}: {$stat->count} settings\n";
}

// Show settings by type
echo "\nSettings by Type:\n";
$typeStats = Capsule::table('system_settings')
    ->selectRaw('type, count(*) as count')
    ->groupBy('type')
    ->orderBy('count', 'desc')
    ->get();

foreach ($typeStats as $stat) {
    echo "  - {$stat->type}: {$stat->count} settings\n";
}

echo "\n🎉 Complete system settings seeder finished successfully!\n";
echo "\nThe system now has a comprehensive set of settings covering:\n";
echo "✅ General application settings\n";
echo "✅ E-commerce configuration\n";
echo "✅ Email system settings\n";
echo "✅ Payment gateway options\n";
echo "✅ Shipping and delivery settings\n";
echo "✅ SEO and marketing settings\n";
echo "✅ Security and authentication\n";
echo "✅ API configuration\n";
echo "✅ Appearance and branding\n";
echo "✅ Notification preferences\n";
