<?php

declare(strict_types=1);

namespace App\Support\Search;

use DefStudio\SearchableInput\DTO\SearchResult;

final class SearchResultPayload
{
    /**
     * Normalise metadata stored inside a SearchResult so every consumer can rely on the
     * same top-level keys. The helper keeps an `id` (original value), a display `label`,
     * and a nested `payload` array that carries the domain specific metadata (SKU, price,
     * URLs, etc.).
     *
     * @param array<string, mixed> $metadata Domain metadata that should live inside `payload`.
     */
    public static function normalise(SearchResult $result, array $metadata = []): SearchResult
    {
        // Always expose the identifier and human readable label to consumers.
        $result
            ->withData('id', $result->value())
            ->withData('label', $result->label());

        // Guarantee payload always includes the identity fields alongside metadata.
        $payload = array_merge([
            'id'    => $result->value(),
            'label' => $result->label(),
        ], $metadata);

        // Bubble the metadata to the top level so legacy widgets that read flattened keys
        // continue to function while the normalised payload remains the canonical structure.
        foreach ($metadata as $key => $value) {
            $result->withData($key, $value);
        }

        // Persist the payload so JS widgets and PHP callbacks read a predictable structure.
        $result->withData('payload', $payload);

        return $result;
    }

    /**
     * Hydrate a normalised representation from either the DTO or an array result.
     * Legacy providers might still emit flat metadata, so we fall back to the raw `data`
     * bag whenever a nested payload is missing.
     *
     * @param  SearchResult|array{value: string, label?: string, data?: array<string, mixed>} $result Normalised DTO or Livewire array payload.
     * @return array{id: string, label: string, payload: array<string, mixed>}
     */
    public static function hydrate(SearchResult|array $result): array
    {
        // Convert array payloads generated by the Livewire component back into the DTO.
        if (is_array($result)) {
            $result = SearchResult::fromArray($result);
        }

        /** @var SearchResult $result */
        $result = $result;

        /** @phpstan-var string $value */
        $value = $result->value();
        $label = $result->label();
        $data = $result->toArray()['data'] ?? [];

        // Respect the normalised payload when it exists; otherwise reuse legacy metadata.
        $payloadSource = is_array($result->get('payload')) ? $result->get('payload') : (is_array($data) ? $data : []);

        // Cast every key to string so PHPStan and downstream consumers consistently handle
        // associative payloads, even if a legacy provider returns numeric indexes.
        $payload = [];
        foreach ($payloadSource as $key => $itemValue) {
            $payload[(string) $key] = $itemValue;
        }

        if (! array_key_exists('id', $payload)) {
            $payload['id'] = $value;
        }

        if (! array_key_exists('label', $payload)) {
            $payload['label'] = $label;
        }

        $normalised = [
            'id'      => $value,
            'label'   => $label,
            'payload' => $payload,
        ];

        /** @var array{id: string, label: string, payload: array<string, mixed>} $normalised */
        $normalised = $normalised;

        return $normalised;
    }
}
